services:
  cloud:
    image: civiform/cloud
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_REGION
      - AZURE_CLIENT_ID
      - AZURE_STORAGE_ACCOUNT_NAME
      - AZURE_LOCAL_CONNECTION_STRING
      - AZURE_STORAGE_ACCOUNT_CONTAINER
      - CONFIG
      - IMAGE_TAG
      - COMMAND
    volumes:
      - ${PWD}/${CONFIG}:/${CONFIG}:ro
    command: cloud/deploys/dev_aws/bin/${COMMAND} --tag=${IMAGE_TAG} --config=${CONFIG}
