package views.admin.programs;

import com.google.common.collect.ImmutableList;
import java.util.Optional;
import lombok.Builder;
import lombok.Data;
import views.BaseViewModel;

/** ViewModel for the program translations page (Thymeleaf). */
@Data
@Builder
public final class ProgramTranslationPageViewModel implements BaseViewModel {

  // Page heading, e.g. "Manage program translations: My Program"
  private final String title;

  // POST target for the translation form
  private final String formActionUrl;
  // English name of the locale being edited, e.g. "Spanish". Used in the save button label.
  private final String displayLanguage;
  // One link per translatable locale, in the order the locales are configured
  private final ImmutableList<LanguageLink> languageLinks;

  // Link to the program details edit page, where the default-locale text for the program
  // details and application steps lives
  private final String editProgramDetailsUrl;
  // Link to the program statuses page, where the default-locale status text lives
  private final String editStatusesUrl;

  // --- Applicant-visible program details ---
  private final TranslationField displayNameField;
  // Only DEFAULT programs have a long description.
  private final boolean showDisplayDescription;
  private final TranslationField displayDescriptionField;
  // External programs have no confirmation screen.
  private final boolean showConfirmationMessage;
  private final TranslationField confirmationMessageField;
  // Only shown when the program has a summary image description configured.
  private final boolean showImageDescription;
  private final TranslationField imageDescriptionField;
  private final TranslationField shortDescriptionField;

  // One section per application step with a default-locale title
  private final ImmutableList<ApplicationStepSection> applicationSteps;
  // One section per configured application status
  private final ImmutableList<StatusSection> statuses;
  // One section per screen. Empty for external programs, which have no screens.
  private final ImmutableList<ScreenSection> screens;

  // Error message shown as a toast (already carries the "Error: " prefix)
  private final Optional<String> errorMessage;
  // Random id for the toast container. Null when there is no error message.
  private final String errorToastId;

  /** A link to translate this program into one of the supported locales. */
  @Data
  @Builder
  public static final class LanguageLink {
    private final String href;
    // The English name of the language, e.g. "Spanish".
    private final String displayLanguage;
    private final boolean selected;
  }

  /** A single translatable field, alongside its default-locale (English) text. */
  @Data
  @Builder
  public static final class TranslationField {
    // Random id generated by the mapper so the label stays associated with the
    // input, matching the ids FieldWithLabel generated for the legacy view.
    private final String id;
    private final String name;
    // The translation in the locale being edited; empty when not yet translated.
    private final String value;
    private final boolean required;
    // Default-locale text, already run through markdown rendering and HTML
    // sanitization, so the template renders it with th:utext.
    private final String defaultTextHtml;
  }

  /** Translation fields for one application step. */
  @Data
  @Builder
  public static final class ApplicationStepSection {
    // 1-based, as shown in the section legend
    private final int stepNumber;
    private final TranslationField titleField;
    private final TranslationField descriptionField;
  }

  /** Translation fields for one application status. */
  @Data
  @Builder
  public static final class StatusSection {
    // Name of the hidden input that tells the form which status the fields belong to
    private final String statusKeyFieldName;
    // The configured (default-locale) status text, which is also the hidden input's value
    private final String statusText;
    private final TranslationField statusNameField;
    // Only statuses with an email body get an email field.
    private final boolean showEmailBody;
    private final TranslationField emailBodyField;
  }

  /** Translation fields for one screen (block). */
  @Data
  @Builder
  public static final class ScreenSection {
    // 1-based, as shown in the section legend
    private final int screenNumber;
    // Link to the block edit page, where the default-locale text lives
    private final String editUrl;
    private final TranslationField nameField;
    private final TranslationField descriptionField;
    // Only screens with an eligibility message configured get this field.
    private final boolean showEligibilityMessage;
    private final TranslationField eligibilityMessageField;
  }
}
