changelog:
  exclude:
    labels:
      - ignore-for-release
      - deploy
      - infrastructure

  categories:
    - title: Features
      labels:
        - '*'

    - title: Bug fixes
      labels:
        - bug

    - title: Dependencies
      labels:
        - dependencies
