changelog:
  exclude:
    labels:
      - ignore-for-release
      - deploy
      - infrastructure

  categories:
    - title: Features
      labels:
        - feature

    - title: Bug fixes
      labels:
        - bug

    - title: Dependencies
      labels:
        - dependencies

    - title: Other changes
      labels:
        - '*'
