reviewers:
  groups:
    i18n-reviewers:
      - team:developers # CiviForm Developers GitHub team

files:
  # The foreign language files, not including `messages`.
  'server/conf/i18n/messages.*':
    - i18n-reviewers

options:
  ignore_draft: true
  enable_group_assignment: false
