reviewers:
  groups:
    i18n-reviewers:
      - team:Developers # CiviForm Developers GitHub team

  per_author:
    transifex-bot:
      - transifex-integration # The Transifex bot's username

files:
  # The foreign language files, not including `messages`.
  'server/conf/i18n/messages.*':
    - i18n-reviewers

options:
  ignore_draft: true
  enable_group_assignment: false

  number_of_reviewers: 1
