package services;

import lombok.Getter;

/** Contains keys into the {@code messages} files used for translation. */
@Getter
public enum MessageKey {
  ACCT_STATUS_LABEL("label.acctStatus"),
  ADDRESS_CORRECTION_LINE_1("content.confirmAddressLine1"),
  ADDRESS_CORRECTION_FOUND_SIMILAR_LINE_2("content.foundSimilarAddressLine2"),
  ADDRESS_CORRECTION_NO_VALID_LINE_2("content.noValidAddressLine2"),
  ADDRESS_VALIDATION_CITY_REQUIRED("validation.cityRequired"),
  ADDRESS_VALIDATION_INVALID_ZIPCODE("validation.invalidZipcode"),
  ADDRESS_VALIDATION_NO_PO_BOX("validation.noPoBox"),
  ADDRESS_VALIDATION_STATE_REQUIRED("validation.stateRequired"),
  ADDRESS_VALIDATION_STREET_REQUIRED("validation.streetRequired"),
  ALERT_ELIGIBILITY_APPLICANT_ELIGIBLE_TITLE("alert.eligibility_applicant_eligible_title"),
  ALERT_ELIGIBILITY_APPLICANT_ELIGIBLE_TEXT("alert.eligibility_applicant_eligible_text"),
  ALERT_ELIGIBILITY_APPLICANT_NOT_ELIGIBLE_TITLE("alert.eligibility_applicant_not_eligible_title"),
  ALERT_ELIGIBILITY_APPLICANT_NOT_ELIGIBLE_TEXT("alert.eligibility_applicant_not_eligible_text"),
  ALERT_ELIGIBILITY_APPLICANT_NOT_ELIGIBLE_TEXT_SHORT(
      "alert.eligibilityApplicantNotEligibleTextShort"), // North Star only
  ALERT_ELIGIBILITY_APPLICANT_FASTFORWARDED_ELIGIBLE_TITLE(
      "alert.eligibility_applicant_fastforwarded_eligible_title"),
  ALERT_ELIGIBILITY_APPLICANT_FASTFORWARDED_ELIGIBLE_TEXT(
      "alert.eligibility_applicant_fastforwarded_eligible_text"),
  ALERT_ELIGIBILITY_APPLICANT_FASTFORWARDED_NOT_ELIGIBLE_TITLE(
      "alert.eligibility_applicant_fastforwarded_not_eligible_title"),
  ALERT_ELIGIBILITY_APPLICANT_FASTFORWARDED_NOT_ELIGIBLE_TEXT(
      "alert.eligibility_applicant_fastforwarded_not_eligible_text"),
  ALERT_ELIGIBILITY_TI_ELIGIBLE_TITLE("alert.eligibility_ti_eligible_title"),
  ALERT_ELIGIBILITY_TI_ELIGIBLE_TEXT("alert.eligibility_ti_eligible_text"),
  ALERT_ELIGIBILITY_TI_NOT_ELIGIBLE_TITLE("alert.eligibility_ti_not_eligible_title"),
  ALERT_ELIGIBILITY_TI_NOT_ELIGIBLE_TEXT("alert.eligibility_ti_not_eligible_text"),
  ALERT_ELIGIBILITY_TI_NOT_ELIGIBLE_TEXT_SHORT(
      "alert.eligibilityTiNotEligibleTextShort"), // North Star only
  ALERT_ELIGIBILITY_TI_FASTFORWARDED_ELIGIBLE_TITLE(
      "alert.eligibility_ti_fastforwarded_eligible_title"),
  ALERT_ELIGIBILITY_TI_FASTFORWARDED_ELIGIBLE_TEXT(
      "alert.eligibility_ti_fastforwarded_eligible_text"),
  ALERT_ELIGIBILITY_TI_FASTFORWARDED_NOT_ELIGIBLE_TITLE(
      "alert.eligibility_ti_fastforwarded_not_eligible_title"),
  ALERT_ELIGIBILITY_TI_FASTFORWARDED_NOT_ELIGIBLE_TEXT(
      "alert.eligibility_ti_fastforwarded_not_eligible_text"),
  ALERT_LIKELY_ELIGIBLE("alert.likelyEligible"), // North Star only
  ALERT_LIKELY_INELIGIBLE("alert.likelyIneligible"), // North Star only
  ALERT_CLIENT_LIKELY_ELIGIBLE("alert.clientLikelyEligible"), // North Star only
  ALERT_CLIENT_LIKELY_INELIGIBLE("alert.clientLikelyIneligible"), // North Star only
  ALERT_NO_PROGRAMS_AVAILABLE("alert.noProgramsAvailable"),
  ALERT_REPEATED_SET_NEW_QUESTION("alert.repeatedSet.newQuestion"),
  ALERT_SUBMITTED("alert.submitted"), // North Star only
  BANNER_ERROR_SAVING_APPLICATION("banner.errorSavingApplication"),
  BANNER_CLIENT_INFO_UPDATED("banner.clientInfoUpdated"),
  BANNER_NEW_CLIENT_CREATED("banner.newClientCreated"),
  BANNER_GOV_WEBSITE_SECTION_HEADER("banner.govWebsiteSectionHeader"),
  BANNER_GOV_WEBSITE_SECTION_CONTENT("banner.govWebsiteSectionContent"),
  BANNER_HOUR("banner.hour"),
  BANNER_HOUR_AND_MINUTE("banner.hourAndMinute"),
  BANNER_HOUR_AND_MINUTES("banner.hourAndMinutes"),
  BANNER_HOURS("banner.hours"),
  BANNER_HOURS_AND_MINUTE("banner.hoursAndMinute"),
  BANNER_HOURS_AND_MINUTES("banner.hoursAndMinutes"),
  BANNER_HTTPS_SECTION_HEADER("banner.httpsSectionHeader"),
  BANNER_HTTPS_SECTION_CONTENT("banner.httpsSectionContent"),
  BANNER_LINK("banner.link"),
  BANNER_MINUTE("banner.minute"),
  BANNER_MINUTES("banner.minutes"),
  BANNER_SESSION_EXPIRATION("banner.sessionExpiration"),
  BANNER_TITLE("banner.title"),
  BUTTON_ADD_NEW_CLIENT("button.addNewClient"),
  BUTTON_BACK_TO_CLIENT_LIST("button.backToClientList"),
  BUTTON_CANCEL("button.cancel"),
  BUTTON_CLOSE("button.close"),
  BUTTON_CREATE_ACCOUNT("button.createAccount"),
  BUTTON_LOGIN("button.login"),
  BUTTON_CLEAR_SEARCH("button.clearSearch"),
  BUTTON_LOGOUT("button.logout"),
  BUTTON_NEXT("button.nextPage"),
  BUTTON_PREVIOUS_SCREEN("button.previousScreen"),
  BUTTON_REPEATED_SET_ADD_NEW("button.repeatedSet.addNew"),
  BUTTON_REPEATED_SET_SUBMIT_NEW("button.repeatedSet.submitNew"),
  BUTTON_REVIEW("button.review"),
  BUTTON_SAVE("button.save"),
  BUTTON_SEARCH("button.search"),
  BUTTON_START_APP("button.startApp"),
  BUTTON_START_APP_LOGIN_ONLY("button.startAppForLoginOnlyProgram"),
  BUTTON_VIEW_APPLICATIONS("button.viewApplications"),
  BUTTON_VIEW_AND_ADD_CLIENTS("button.viewAndAddClients"),
  CURRENCY_VALIDATION_MISFORMATTED("validation.currencyMisformatted"),
  CONTACT_INFO_LABEL("label.contactInfo"),
  CONTENT_ADMIN_FOOTER_PROMPT("content.adminFooterPrompt"),
  CONTENT_BLOCK_PROGRESS("content.blockProgress"),
  CONTENT_CLIENT_CREATED("content.clientCreated"),
  CONTENT_CONFIRMED("content.confirmed"),
  CONTENT_EMAIL_TOOLTIP("content.emailTooltip"),
  CONTENT_FIND_PROGRAMS("content.findPrograms"),
  CONTENT_NUMBER_OF_APP_SUBMITTED("content.numberOfAppSubmitted"),
  CONTENT_ONE_APP_SUBMITTED("content.oneAppSubmitted"),
  CONTENT_OPTIONAL("content.optional"),
  ERROR_EMAIL_IN_USE_CLIENT_CREATE("label.errorEmailInUseForClientCreate"),
  ERROR_EMAIL_IN_USE_CLIENT_EDIT("label.errorEmailInUseForClientEdit"),
  ERROR_FIRST_NAME("label.errorFirstName"),
  ERROR_LAST_NAME("label.errorLastName"),
  DATE_VALIDATION_INVALID_DATE_FORMAT("validation.invalidDateFormat"),
  DATE_VALIDATION_DATE_BEYOND_ALLOWABLE_YEARS_IN_PAST("validation.dateBeyondAllowablePast"),
  DATE_VALIDATION_DATE_BEYOND_ALLOWABLE_YEARS_IN_FUTURE("validation.dateBeyondAllowableFuture"),
  DATE_VALIDATION_DOB_NOT_IN_PAST("validation.dobNotInPast"),
  DATE_VALIDATION_IMPOSSIBLE_DOB("validation.impossibleDob"),
  DATE_VALIDATION_FUTURE_DATE_REQUIRED("validation.futureDateRequired"),
  DATE_VALIDATION_DATE_TOO_FAR_IN_PAST("validation.dateTooFarInPast"),
  DATE_VALIDATION_PAST_DATE_REQUIRED("validation.pastDateRequired"),
  DATE_VALIDATION_DATE_TOO_FAR_IN_FUTURE("validation.dateTooFarInFuture"),
  DATE_VALIDATION_DATE_NOT_IN_RANGE("validation.dateNotInRange"),
  DATE_VALIDATION_CURRENT_DATE_REQUIRED("validation.currentDateRequired"),
  DAY_LABEL("label.day"),
  DOB_EXAMPLE("label.dobExample"),
  DOB_ERROR_LABEL("label.errorDOB"),
  DOB_LABEL("label.dob"),
  DROPDOWN_PLACEHOLDER("placeholder.noDropdownSelection"),
  END_SESSION("header.endSession"),
  END_YOUR_SESSION("banner.endYourSession"),
  EMAIL_APPLICATION_RECEIVED_BODY("email.applicationReceivedBody"),
  EMAIL_APPLICATION_RECEIVED_SUBJECT("email.applicationReceivedSubject"),
  EMAIL_APPLICATION_UPDATE_SUBJECT("email.applicationUpdateSubject"),
  EMAIL_LOGIN_TO_CIVIFORM("email.loginToCiviform"),
  EMAIL_TI_APPLICATION_SUBMITTED_BODY("email.tiApplicationSubmittedBody"),
  EMAIL_TI_APPLICATION_SUBMITTED_SUBJECT("email.tiApplicationSubmittedSubject"),
  EMAIL_TI_APPLICATION_UPDATE_SUBJECT("email.tiApplicationUpdateSubject"),
  EMAIL_TI_MANAGE_YOUR_CLIENTS("email.tiManageYourClients"),
  EMAIL_LABEL("label.email"),
  ENUMERATOR_VALIDATION_DUPLICATE_ENTITY_NAME("validation.duplicateEntityName"),
  ENUMERATOR_VALIDATION_ENTITY_REQUIRED("validation.entityNameRequired"),
  ENUMERATOR_VALIDATION_TOO_MANY_ENTITIES("validation.tooManyEntities"),
  ENUMERATOR_VALIDATION_TOO_FEW_ENTITIES("validation.tooFewEntities"),
  ERROR_INCOMPLETE_DATE("error.incompleteDate"),
  FILEUPLOAD_VALIDATION_FILE_REQUIRED("validation.fileRequired"),
  FILEUPLOAD_VALIDATION_FILE_TOO_LARGE("validation.fileTooLarge"),
  FOOTER_SUPPORT_LINK_DESCRIPTION("footer.supportLinkDescription"),
  GUEST("guest"),
  GUEST_INDICATOR("header.guestIndicator"),
  HEADER_ACCT_SETTING("header.acctSettings"),
  HEADER_CLIENT_LIST("header.clientList"),
  HEADER_SEARCH("header.search"),
  HEADING_INFORMATION_ARIA_LABEL_PREFIX("heading.informationAriaLabelPrefix"), // North Star only
  HEADING_REPEATED_SET_CREATION_METHOD("heading.repeatedSet.creationMethod"),
  HEADING_REVIEW_AND_SUBMIT("heading.reviewAndSubmit"), // North Star only
  HEADING_SUCCESS_ARIA_LABEL_PREFIX("heading.successAriaLabelPrefix"), // North Star only
  ID_VALIDATION_NUMBER_REQUIRED("validation.numberRequired"),
  ID_VALIDATION_TOO_LONG("validation.idTooLong"),
  ID_VALIDATION_TOO_SHORT("validation.idTooShort"),
  INPUT_LISTED_ENTITY("input.repeatedSet.listedEntity"),
  INPUT_REPEATED_SET_ADMIN_ID("input.repeatedSet.adminId"),
  INPUT_REPEATED_SET_HINT_TEXT("input.repeatedSet.hintText"),
  INPUT_REPEATED_SET_MIN_ENTITIES("input.repeatedSet.minEntities"),
  INPUT_REPEATED_SET_MAX_ENTITIES("input.repeatedSet.maxEntities"),
  INPUT_REPEATED_SET_QUESTION_TEXT("input.repeatedSet.questionText"),
  INVALID_INPUT("validation.invalidInput"),
  LABEL_NEW_REPEATED_SET_FORM("label.repeatedSet.newSetForm"),
  LANGUAGE_LABEL_SR("label.languageSr"),
  LINK_ADMIN_LOGIN("link.adminLogin"),
  LINK_EDIT("link.edit"),
  LINK_OPENS_NEW_TAB_SR("link.opensNewTabSr"),
  LINK_PROGRAM_DETAILS("link.programDetails"),
  MAP_VALIDATION_TOO_MANY("map.validation.tooManySelections"),
  MEMORABLE_DATE_PLACEHOLDER("placeholder.memorableDate"),
  MODAL_ERROR_SAVING_CONTENT_REVIEW("modal.errorSaving.content.review"), // North Star only
  MODAL_ERROR_SAVING_CONTENT_PREVIOUS("modal.errorSaving.content.previous"), // North Star only
  MODAL_ERROR_SAVING_CONTINUE_BUTTON_REVIEW(
      "modal.errorSaving.continueButton.review"), // North Star only
  MODAL_ERROR_SAVING_CONTINUE_BUTTON_PREVIOUS(
      "modal.errorSaving.continueButton.previous"), // North Star only
  MULTI_OPTION_VALIDATION("adminValidation.multiOptionEmpty"),
  MULTI_OPTION_ADMIN_VALIDATION("adminValidation.multiOptionAdminError"),
  MULTI_SELECT_VALIDATION_TOO_FEW("validation.tooFewSelections"),
  MULTI_SELECT_VALIDATION_TOO_MANY("validation.tooManySelections.v2"),
  NAME_EXAMPLE("label.nameExample"),
  NAME_LABEL_FIRST("label.firstName"),
  NAME_LABEL_LAST("label.lastName"),
  NAME_LABEL_MIDDLE("label.middleName"),
  NAME_LABEL_SUFFIX("label.nameSuffix"),
  NAME_VALIDATION_FIRST_REQUIRED("validation.firstNameRequired"),
  NAME_VALIDATION_LAST_REQUIRED("validation.lastNameRequired"),
  OPTION_MEMORABLE_DATE_JANUARY("option.memorableDate.January"),
  OPTION_MEMORABLE_DATE_FEBRUARY("option.memorableDate.February"),
  OPTION_MEMORABLE_DATE_MARCH("option.memorableDate.March"),
  OPTION_MEMORABLE_DATE_APRIL("option.memorableDate.April"),
  OPTION_MEMORABLE_DATE_MAY("option.memorableDate.May"),
  OPTION_MEMORABLE_DATE_JUNE("option.memorableDate.June"),
  OPTION_MEMORABLE_DATE_JULY("option.memorableDate.July"),
  OPTION_MEMORABLE_DATE_AUGUST("option.memorableDate.August"),
  OPTION_MEMORABLE_DATE_SEPTEMBER("option.memorableDate.September"),
  OPTION_MEMORABLE_DATE_OCTOBER("option.memorableDate.October"),
  OPTION_MEMORABLE_DATE_NOVEMBER("option.memorableDate.November"),
  OPTION_MEMORABLE_DATE_DECEMBER("option.memorableDate.December"),
  OPTION_REPEATED_SET_CHOOSE_EXISTING("option.repeatedSet.chooseExisting"),
  OPTION_REPEATED_SET_CREATE_NEW("option.repeatedSet.createNew"),
  OPTION_YES("option.yes"),
  OPTION_NO("option.no"),
  OPTION_NOT_SURE("option.notSure"),
  OPTION_MAYBE("option.maybe"),
  PHONE_NUMBER_LABEL("label.phoneNum"),
  PHONE_VALIDATION_NUMBER_REQUIRED("validation.phoneNumberRequired"),
  PHONE_VALIDATION_NON_NUMBER_VALUE("validation.phoneNumberMustContainNumbersOnly"),
  PHONE_VALIDATION_INVALID_PHONE_NUMBER("validation.invalidPhoneNumberProvided"),
  PHONE_VALIDATION_NUMBER_NOT_IN_COUNTRY("validation.phoneMustBeLocalToCountry"),
  SEARCH_BY_DOB("label.searchByDob"),
  SEARCH_BY_NAME("label.searchByName"),
  MONTH_LABEL("label.month"),
  NAME_LABEL("label.name"),
  NOTES_LABEL("label.notes"),
  NOT_FOR_PRODUCTION_BANNER_LINE_1("banner.notForProductionBannerLine1"),
  NOT_FOR_PRODUCTION_BANNER_LINE_2("banner.notForProductionBannerLine2"),
  NUMBER_VALIDATION_TOO_BIG("validation.numberTooBig"),
  NUMBER_VALIDATION_TOO_SMALL("validation.numberTooSmall"),
  NUMBER_VALIDATION_NON_INTEGER("validation.numberNonInteger"),
  REQUIRED_FIELDS_NOTE("content.requiredFieldsNote"),
  TAG_MAY_NOT_QUALIFY("tag.mayNotQualify"),
  TAG_MAY_NOT_QUALIFY_TI("tag.mayNotQualifyTi"),
  TAG_MAY_QUALIFY("tag.mayQualify"),
  TAG_MAY_QUALIFY_TI("tag.mayQualifyTi"),
  TEXT_NESTED_REPEATED_SET("text.nestedRepeatedSet"),
  TEXT_REPEATED_SET("text.repeatedSet"),
  TEXT_VALIDATION_TOO_LONG("validation.textTooLong"),
  TEXT_VALIDATION_TOO_SHORT("validation.textTooShort"),
  TITLE_ALL_CLIENTS("title.allClients"),
  TITLE_APPLICATION_CONFIRMATION("title.applicationConfirmation"),
  TITLE_CREATE_CLIENT("title.createClient"),
  TITLE_PRE_SCREENER_SUMMARY("title.preScreenerSummary"),
  TITLE_DISPLAY_ALL_CLIENTS("title.displayingAllClients"),
  TITLE_DISPLAY_MULTI_CLIENTS("title.displayingMultiClients"),
  TITLE_DISPLAY_ONE_CLIENT("title.displayingOneClient"),
  TITLE_EDIT_CLIENT("title.editClient"),
  TITLE_INELIGIBLE("title.ineligible"),
  TITLE_ORG_MEMBERS("title.orgMembers"),
  TITLE_PROGRAM_OVERVIEW("title.programOverview"),
  TITLE_PROGRAM_SUMMARY("title.programSummary"),
  TITLE_TI_ACCOUNT_SETTINGS("title.tiAccountSettings"),
  TITLE_TI_DASHBOARD("title.tiDashboard"),
  TOAST_APPLICATION_OUT_OF_DATE("toast.applicationOutOfDate"),
  TOAST_ERROR_MSG_OUTLINE("toast.errorMessageOutline"),
  USER_NAME("header.userName"),
  VALIDATION_REQUIRED("validation.isRequired"),
  YEAR_LABEL("label.year"),

  // Session timeout related messages
  SESSION_INACTIVITY_WARNING_TITLE("session.inactivity.warning.title"),
  SESSION_INACTIVITY_WARNING_MESSAGE("session.inactivity.warning.message"),
  SESSION_LENGTH_WARNING_TITLE("session.length.warning.title"),
  SESSION_LENGTH_WARNING_MESSAGE("session.length.warning.message"),
  SESSION_EXTEND_BUTTON("session.extend.button"),
  SESSION_EXTENDED_SUCCESS("session.extended.success"),
  SESSION_EXTENDED_ERROR("session.extended.error");

  private final String keyName;

  MessageKey(String keyName) {
    this.keyName = keyName;
  }
}
