#! /usr/bin/env bash

source "cloud/azure/bin/lib.sh"

set -e

while getopts g:s: flag
do
  case "${flag}" in
    g) resource_group="${OPTARG}";;
    *) out::error "Unexpected getopts value ${flag}";;
  esac
done


readonly APP_NAME="$(azure::get_app_name "${resource_group}")"
readonly CANARY_URL="$(azure::get_canary_url "${resource_group}" "${APP_NAME}")"
readonly PRIMARY_URL="$(azure::get_primary_url "${resource_group}" "${APP_NAME}")"

azure::slot_setting "canary" "${APP_NAME}" "BASE_URL" "https://${CANARY_URL}" "${resource_group}"
azure::slot_setting "primary" "${APP_NAME}" "BASE_URL" "https://${PRIMARY_URL}" "${resource_group}"

# If we're deploying a dev instance, we want the staging hostname to match the app's BASE_URL
azure::slot_setting "canary" "${APP_NAME}" "STAGING_HOSTNAME" "${CANARY_URL}" "${resource_group}"
azure::slot_setting "primary" "${APP_NAME}" "STAGING_HOSTNAME" "${PRIMARY_URL}" "${resource_group}"


