services:
  db:
    image: postgres:16.10@sha256:fb9aa6d07b0fe53e94e8470977f316d1cdb39b8cdb33c45279ff0bbe32067c25
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

  civiform:
    platform: linux/amd64
    image: civiform:prod
    restart: always
    container_name: civiform_prod
    ports:
      - 8888:9000
    environment:
      # Randomly generated value to comply with Play's secret length
      - SECRET_KEY=K5SgucxBYC3xJwNcGWZV1Y7uASmrc+SqftbcTROH0s8=
      - APPLICANT_OIDC_CLIENT_ID=client
      - APPLICANT_OIDC_CLIENT_SECRET=notarealsecret
      - APPLICANT_OIDC_DISCOVERY_URI=https://civiform-staging.us.auth0.com/.well-known/openid-configuration
      - CIVIFORM_APPLICANT_IDP=auth0
