version: '3.1'

services:
  db:
    image: postgres:12.14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

  civiform:
    platform: linux/amd64
    image: civiform:prod
    restart: always
    container_name: civiform_prod
    links:
      - 'db:database'
    ports:
      - 8888:9000
    environment:
      - SECRET_KEY=notarealsecret
      - IDCS_CLIENT_ID=client
      - IDCS_SECRET=notarealsecret
      - ADMIN_SETTINGS_PANEL_ENABLED=true
