version: '3.1'

services:
  db:
    image: postgres:12.5
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

  civiform:
    image: civiform:prod
    restart: always
    container_name: play
    links:
      - 'db:database'
    ports:
      - 9000:9000
    environment:
      - IDCS_CLIENT_ID=client
      - IDCS_SECRET=SECRET_KEY
      - SECRET_KEY
