# Use postgres/example user/password credentials
version: '3.8'

services:
  civiform:
    image: civiform-dev
    restart: always
    volumes:
      - ./universal-application-tool-0.0.1:/usr/src/universal-application-tool-0.0.1
      - ./sbt_cache/coursier:/root/.cache/coursier
      - ~/.sbt:/root/.sbt
      - ~/.ivy:/root/.ivy2
