package views.admin.questions;

import com.google.common.collect.ImmutableList;
import java.util.Optional;
import lombok.Builder;
import lombok.Data;
import views.BaseViewModel;

/** ViewModel for the question translations page (Thymeleaf). */
@Data
@Builder
public final class QuestionTranslationPageViewModel implements BaseViewModel {

  // Page heading, e.g. "Manage question translations: my-question"
  private final String title;

  // POST target for the translation form
  private final String formActionUrl;
  // Link to the question edit page, where the default-locale text lives
  private final String editDefaultUrl;
  // Submit button label, e.g. "Save Spanish updates"
  private final String saveButtonText;

  private final String concurrencyToken;

  // One link per translatable locale, in the order the locales are configured
  private final ImmutableList<LanguageLink> languageLinks;

  // --- Applicant-visible question details ---
  private final TranslationField questionTextField;
  // Null when the question has no help text in the default locale.
  private final TranslationField questionHelpTextField;
  private final boolean showHelpText;

  // --- Question-type specific fields. At most one of these applies. ---

  // YES_NO: the options are pre-translated, so only a note is rendered.
  private final boolean showYesNoNote;

  // CHECKBOX / DROPDOWN / RADIO_BUTTON
  private final boolean showAnswerOptions;
  private final ImmutableList<TranslationField> answerOptionFields;

  // ENUMERATOR
  private final boolean showEntityType;
  // Null unless the question is an enumerator.
  private final TranslationField entityTypeField;

  // MAP. The legacy view rendered the settings fieldset whenever the question
  // had any settings, even when none of them were translatable, so this is not
  // simply "mapSettingFields is non-empty".
  private final boolean showMapSettings;
  private final ImmutableList<TranslationField> mapSettingFields;

  // Error message shown as a toast (already carries the "Error: " prefix)
  private final Optional<String> errorMessage;
  // Random id for the toast container. Null when there is no error message.
  private final String errorToastId;

  /** A link to translate this question into one of the supported locales. */
  @Data
  @Builder
  public static final class LanguageLink {
    private final String href;
    // The English name of the language, e.g. "Spanish".
    private final String displayLanguage;
    private final boolean selected;
  }

  /** A single translatable field, alongside its default-locale (English) text. */
  @Data
  @Builder
  public static final class TranslationField {
    // Random id generated by the mapper so the label stays associated with the
    // input, matching the ids FieldWithLabel generated for the legacy view.
    private final String id;
    private final String name;
    private final String label;
    private final String value;
    // Whether to render a textarea (true) or a text input (false).
    private final boolean textarea;
    // Whether to render the "Markdown is supported" indicator. Textareas only.
    private final boolean markdown;
    // Default-locale text, already run through markdown rendering and HTML
    // sanitization, so the template renders it with th:utext.
    private final String defaultTextHtml;
  }
}
