AWSTemplateFormatVersion: '2010-09-09'
Description: 'The containers and service configuration for CiviForm.'
Mappings:
  Images:
    prod:
      image: public.ecr.aws/t1q6b4h2/universal-application-tool:prod
    staging:
      image: public.ecr.aws/t1q6b4h2/universal-application-tool:latest
  Notifications:
    prod:
      sender: civiform-notification@seattle.gov
    staging:
      sender: noreply@staging.seattle.civiform.com
  AdminGroup:
    prod:
      group: ad\ITD_CiviForm_Admins
    staging:
      group: ad\ITD_CiviForm_Admins_Test
  Registration:
    prod:
      uri: https://login.seattle.gov/#/registration?appName=CiviForm
    staging:
      uri: https://qalogin.seattle.gov:12443/#/registration?appName=CIVIFORM_STAGE
Parameters:
  Environment:
    Type: String
    AllowedValues: ["staging", "prod"]
    Description: "Staging or prod environment"
  S3TaskRole:
    Description: The task role for the containers.
    Type: String
  DBAddress:
    Description: The address at which the database can be reached.
    Type: String
  DBPort:
    Description: The port on which the database can be reached.
    Type: String
  LBTargetName:
    Description: The load balancer target group to add new containers to.
    Type: String
  ContainerSecurityGroup:
    Description: The security group to use for the containers.
    Type: String
  PrivateSubnet1:
    Description: The private subnets to add the database to.
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2:
    Description: The private subnet to add the database to.
    Type: AWS::EC2::Subnet::Id
  S3BucketName:
    Description: S3 bucket name for file storage.
    Type: String
  DBUsername:
    NoEcho: 'true'
    Description: Username for database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  DBPassword:
    NoEcho: 'true'
    Description: Password for database access
    Type: String
  SecretKey:
    NoEcho: 'true'
    Description: Secret key for Play application
    Type: String
  DomainName:
    Description: The domain name to use as the base URL.
    Type: String
  MeasurementId:
    Description: The Google Analytics measurement ID.
    Type: String
Resources:
  ecscluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Join ["-", [!Ref Environment, "civiform-fargate-cluster"]]
      CapacityProviders:
        - FARGATE
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
  ecsservice:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref 'ecscluster'
      DesiredCount: 2
      TaskDefinition: !Ref 'ecstaskdef'
      LoadBalancers:
        - ContainerName: !Join ["-", [!Ref Environment, "civiform-container"]]
          ContainerPort: 9000
          TargetGroupArn: !Ref 'LBTargetName'
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref 'ContainerSecurityGroup'
          Subnets:
            - !Ref 'PrivateSubnet1'
            - !Ref 'PrivateSubnet2'
  loggroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join [".", [!Ref Environment, "civiform.lg"]]
      RetentionInDays: 90
  ecstaskdef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities:
        - FARGATE
      TaskRoleArn: !Ref S3TaskRole
      ExecutionRoleArn: arn:aws:iam::405662711265:role/ecs-task-role
      NetworkMode: awsvpc
      Cpu: 1024
      Memory: 8192
      ContainerDefinitions:
        - Name: !Join ["-", [!Ref Environment, "civiform-container"]]
          Image: !FindInMap [Images, !Ref Environment, image]
          Environment:
            - Name: DB_JDBC_STRING
              Value: !Join
                - ''
                - - jdbc:postgresql://
                  - !Ref 'DBAddress'
                  - ':'
                  - !Ref 'DBPort'
                  - /postgres
            - Name: DB_USERNAME
              Value: !Ref 'DBUsername'
            - Name: DB_PASSWORD
              Value: !Sub '{{resolve:secretsmanager:${DBPassword}}}'
            - Name: SECRET_KEY
              Value: !Sub '{{resolve:secretsmanager:${SecretKey}}}'
            - Name: AWS_REGION
              Value: !Sub '${AWS::Region}'
            - Name: AWS_SES_SENDER
              Value: !FindInMap [Notifications, !Ref Environment, sender]
            - Name: AWS_S3_BUCKET_NAME
              Value: !Ref 'S3BucketName'
            - Name: IDCS_CLIENT_ID
              Value: !Sub '{{resolve:secretsmanager:${Environment}-oidc-secrets:SecretString:IDCS_CLIENT_ID}}'
            - Name: IDCS_SECRET
              Value: !Sub '{{resolve:secretsmanager:${Environment}-oidc-secrets:SecretString:IDCS_SECRET}}'
            - Name: IDCS_DISCOVERY_URI
              Value: !Sub '{{resolve:secretsmanager:${Environment}-oidc-secrets:SecretString:IDCS_DISCOVERY_URI}}'
            - Name: ADFS_CLIENT_ID
              Value: !Sub '{{resolve:secretsmanager:${Environment}-oidc-secrets:SecretString:ADFS_CLIENT_ID}}'
            - Name: ADFS_SECRET
              Value: !Sub '{{resolve:secretsmanager:${Environment}-oidc-secrets:SecretString:ADFS_SECRET}}'
            - Name: IDCS_REGISTER_URI
              Value: !FindInMap [Registration, !Ref Environment, uri]
            - Name: ADFS_GLOBAL_ADMIN_GROUP
              Value: !FindInMap [AdminGroup, !Ref Environment, group]
            - Name: BASE_URL
              Value: !Sub "https://${DomainName}"
            - Name: MEASUREMENT_ID
              Value: !Sub "${MeasurementId}"
          Cpu: 1024
          Memory: 8192
          PortMappings:
            - ContainerPort: '9000'
              HostPort: '9000'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref 'loggroup'
              awslogs-region: !Sub '${AWS::Region}'
              awslogs-stream-prefix: civiformsrv
          Essential: true
  autoscalingtarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MinCapacity: 2
      MaxCapacity: 5
      ResourceId: !Join ['/', [service, !Ref ecscluster, !GetAtt ecsservice.Name]]
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs
      RoleARN: arn:aws:iam::405662711265:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService
  autoscalingpolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: CiviFormAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref autoscalingtarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        ScaleInCooldown: 10
        ScaleOutCooldown: 10
        # Keep things at or lower than 75% CPU utilization
        TargetValue: 75
Outputs:
  ECSService:
    Description: The ARN of the service.
    Value: !Ref 'ecsservice'
    Export:
      Name: !Sub '${AWS::StackName}-ECSService'
  ECSCluster:
    Description: The ARN of the cluster.
    Value: !GetAtt 'ecscluster.Arn'
    Export:
      Name: !Sub '${AWS::StackName}-ECSCluster'
