AWSTemplateFormatVersion: '2010-09-09'
Description: ''
Parameters:
  DBUsername:
    NoEcho: 'true'
    Description: Username for database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  DBPassword:
    NoEcho: 'true'
    Description: Password for database access
    Type: String
    MinLength: '16'
    MaxLength: '64'
  SecretKey:
    NoEcho: 'true'
    Description: Secret key for Play application
    Type: String
    MinLength: '12'
    MaxLength: '64'
  Timestamp:
    Description: Current timestamp in seconds.
    Type: Number
Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/seattle-uat-cftmpl/${Timestamp}/network.yaml'
  SecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/seattle-uat-cftmpl/${Timestamp}/security_groups.yaml'
      Parameters:
        VPCId: !GetAtt 'VPC.Outputs.VPCId'
  LB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/seattle-uat-cftmpl/${Timestamp}/load_balancer.yaml'
      Parameters:
        VPCId: !GetAtt 'VPC.Outputs.VPCId'
        PublicSubnet1: !GetAtt 'VPC.Outputs.PublicSubnet1'
        PublicSubnet2: !GetAtt 'VPC.Outputs.PublicSubnet2'
        LBSecurityGroup: !GetAtt 'SecurityGroups.Outputs.LbGroup'
  DB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/seattle-uat-cftmpl/${Timestamp}/database.yaml'
      Parameters:
        DBUsername: !Ref 'DBUsername'
        DBPassword: !Ref 'DBPassword'
        DBSecurityGroup: !GetAtt 'SecurityGroups.Outputs.DatabaseGroup'
        PrivateSubnet1: !GetAtt 'VPC.Outputs.PrivateSubnet1'
        PrivateSubnet2: !GetAtt 'VPC.Outputs.PrivateSubnet2'
  Container:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/seattle-uat-cftmpl/${Timestamp}/containers.yaml'
      Parameters:
        DBUsername: !Ref 'DBUsername'
        DBPassword: !Ref 'DBPassword'
        DBAddress: !GetAtt 'DB.Outputs.DBAddress'
        DBPort: !GetAtt 'DB.Outputs.DBPort'
        SecretKey: !Ref 'SecretKey'
        PrivateSubnet1: !GetAtt 'VPC.Outputs.PrivateSubnet1'
        PrivateSubnet2: !GetAtt 'VPC.Outputs.PrivateSubnet2'
        LBTargetName: !GetAtt 'LB.Outputs.LBTarget'
        ContainerSecurityGroup: !GetAtt 'SecurityGroups.Outputs.ContainerGroup'
