package repository;

import static java.util.concurrent.CompletableFuture.supplyAsync;
import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;

import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;
import io.ebean.BeanState;
import io.ebean.DB;
import io.ebean.Database;
import io.ebean.FetchConfig;
import io.ebean.Query;
import io.ebean.Transaction;
import io.ebean.TxScope;
import io.ebean.annotation.TxIsolation;
import java.util.Locale;
import java.util.concurrent.atomic.AtomicInteger;
import junitparams.JUnitParamsRunner;
import junitparams.Parameters;
import models.AccountModel;
import models.CategoryModel;
import models.LifecycleStage;
import models.ProgramModel;
import models.QuestionModel;
import models.VersionModel;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import services.LocalizedStrings;
import services.question.types.QuestionDefinition;
import services.question.types.QuestionDefinitionConfig;
import services.question.types.TextQuestionDefinition;
import support.ProgramBuilder;

/**
 * Ebean documentation is unfortunately sparse without a lot of practical examples.
 *
 * <p>The following serves as documentation and verification of believed invariants in how Ebean
 * actually operates, and possibly serves as a guard for changes in future Ebean releases.
 */
@RunWith(JUnitParamsRunner.class)
public class EbeanInvariantTest extends ResetPostgres {

  private static final QuestionDefinition QUESTION_DEFINITION =
      new TextQuestionDefinition(
          QuestionDefinitionConfig.builder()
              .setName("question")
              .setDescription("applicant's name")
              .setQuestionText(LocalizedStrings.of(Locale.US, "What is your name?"))
              .setQuestionHelpText(LocalizedStrings.empty())
              .build());

  private Database database;

  @Before
  public void setup() {
    database = DB.getDefault();
  }

  /*  Auto generated ID tests.
   *
   * When a new Model is added to the database, auto generated IDs are created
   * and set on the object automatically.
   *
   * The exception to this is for Batch queries where they are not, because the
   * insert has most likely not been sent to the DB which generates the IDs.
   */

  @Test
  public void autoGeneratedIds_areAutoSetOnObjects_save() {
    QuestionModel questionModel = new QuestionModel(QUESTION_DEFINITION);
    assertNull(questionModel.id);

    questionModel.save();

    assertNotNull(questionModel.id);
    assertThat(questionModel.id).isGreaterThanOrEqualTo(0);
  }

  @Test
  public void autoGeneratedIds_areAutoSetOnObjects_insert() {
    QuestionModel questionModel = new QuestionModel(QUESTION_DEFINITION);
    assertNull(questionModel.id);

    questionModel.insert();

    assertNotNull(questionModel.id);
    assertThat(questionModel.id).isGreaterThanOrEqualTo(0);
  }

  /* Note that we're not calling Transaction.commit() through the Transaction
  cases, partially because it's not needed for these tests, as well it
  illustrates what's true without a commit(). */

  @Test
  public void autoGeneratedIds_areAutoSetOnObjects_withTransaction() {
    try (Transaction ignore =
        database.beginTransaction(TxScope.required().setIsolation(TxIsolation.SERIALIZABLE))) {
      QuestionModel questionModel = new QuestionModel(QUESTION_DEFINITION);
      assertNull(questionModel.id);

      questionModel.save();

      assertNotNull(questionModel.id);
      assertThat(questionModel.id).isGreaterThanOrEqualTo(0);
    }
  }

  @Test
  public void autoGeneratedIds_areNotAutoSetOnObjects_withBatchTransaction_mustRefresh() {
    try (Transaction transaction =
        database.beginTransaction(TxScope.required().setIsolation(TxIsolation.SERIALIZABLE))) {
      transaction.setBatchMode(true);
      QuestionModel questionModel = new QuestionModel(QUESTION_DEFINITION);
      assertNull(questionModel.id);

      questionModel.save();

      // ID is NOT set because the save is queued in the server.
      assertNull(questionModel.id);

      // Must refresh to get the ID.
      // Does a select statement for the ID which Ebean seems to know already,
      // this should update M2M properties too.
      questionModel.refresh();

      assertNotNull(questionModel.id);
      assertThat(questionModel.id).isGreaterThanOrEqualTo(0);
    }
  }

  @Test
  public void autoGeneratedIds_areNotAutoSetOnObjects_withBatchTransaction_canFlush() {
    try (Transaction transaction =
        database.beginTransaction(TxScope.required().setIsolation(TxIsolation.SERIALIZABLE))) {
      transaction.setBatchMode(true);
      QuestionModel questionModel = new QuestionModel(QUESTION_DEFINITION);
      assertNull(questionModel.id);

      questionModel.save();

      // ID is NOT set because the save is queued in the server.
      assertNull(questionModel.id);

      // Flushing sends the batch to the DB prematurely.
      // Needing to flush in a batch may indicate a data flow smell, but is possibly still better
      // than not batching.
      // This does no additional select, Ebean already knows the ID, note that other information
      // like M2M relations are likely not updated which refresh() does.
      // transaction.commit() is identical to flush it seems.
      questionModel.flush();

      // ID is now set.
      assertNotNull(questionModel.id);
      assertThat(questionModel.id).isGreaterThanOrEqualTo(0);
    }
  }

  /* Transactions */

  /**
   * When using TxScope.required(), as we should, inner transactions become part of outer ones with
   * the top level one ultimately having control over commiting or not.
   *
   * <p>Savepoints do not change this behavior. See later for Savepoint usage.
   */
  @Test
  @Parameters({"false", "true"})
  public void transaction_innerIsNotIsolated(Boolean useSavepoint) {
    assertThat(DB.find(AccountModel.class).findCount()).isEqualTo(0);
    try (Transaction outerTransaction =
        DB.beginTransaction(TxScope.required().setIsolation(TxIsolation.SERIALIZABLE))) {

      if (useSavepoint) {
        outerTransaction.setNestedUseSavepoint();
      }

      try (Transaction innerTransaction =
          DB.beginTransaction(TxScope.required().setIsolation(TxIsolation.SERIALIZABLE))) {
        new AccountModel().insert();
        // Within the inner transaction we see the new account.
        assertThat(DB.find(AccountModel.class).findCount()).isEqualTo(1);
        // This commit is required to save the changes, but doesn't actually
        // commit to the database because it isn't on the outermost transaction.
        innerTransaction.commit();
      }

      // In the outer transaction we see the new account.
      assertThat(DB.find(AccountModel.class).findCount()).isEqualTo(1);

      // Note: No commit to simulate that the outer transaction controls everything
      // try-with-resources handles the rollback/end.
    }

    // Outside of both transactions, everything is rolled back.
    assertThat(DB.find(AccountModel.class).findCount()).isEqualTo(0);
  }

  /**
   * Not commiting in an inner transaction causes weirdness.
   *
   * <p>This is a good reason to use TransactionManager.execute()
   */
  @Test
  public void transaction_mustCommitInInnerTransaction() {
    final long outerAccountId;
    assertThat(DB.find(AccountModel.class).findCount()).isEqualTo(0);
    try (Transaction outerTransaction =
        DB.beginTransaction(TxScope.required().setIsolation(TxIsolation.SERIALIZABLE))) {
      new AccountModel().insert();

      // Enabling nested savepoints produces the expected behavior where
      // nothing is saved from the transactions:
      // outerTransaction.setNestedUseSavepoint();
      try (Transaction innerTransaction =
          DB.beginTransaction(TxScope.required().setIsolation(TxIsolation.SERIALIZABLE))) {
        new AccountModel().insert();
        // Assert that from within this inner transaction, we see the new account
        assertThat(DB.find(AccountModel.class).findCount()).isEqualTo(2);
        // Not commiting seems to create the problem.
        // A rollback is done here as expected.
      }

      // WARNING: We don't see the inner data as expected, but we also don't see the first one
      // made before innerTransaction! The inner rollback affected everything since the start of the
      // outer transaction. If we used setNestedUseSavepoint() the initial data would still exist.
      assertThat(DB.find(AccountModel.class).findCount()).isEqualTo(0);

      // From the logs we see a new transaction is used starting here.
      // The issue is also triggered by this .insert(). The expected outcome
      // where the last assert outside the transactions sees nothing happens
      // without this insert.
      var account = new AccountModel();
      account.insert();
      outerAccountId = account.id;
      // We see the new one in the outer.
      assertThat(DB.find(AccountModel.class).findCount()).isEqualTo(1);

      // WARNING: TXN logging shows a commit happens, despite it not being here.
    }

    // For some reason we see the outer one.
    assertThat(DB.find(AccountModel.class).findIds()).containsExactly(outerAccountId);
  }

  /**
   * Rolling back some but not all of a transaction doesn't usually make sense for our code but
   * nested savepoints is how to do that.
   */
  @Test
  public void transaction_nestedSavePointsAllowForInnerRollbacks() {
    final long outerAccountId;
    assertThat(DB.find(AccountModel.class).findCount()).isEqualTo(0);
    try (Transaction outerTransaction =
        DB.beginTransaction(TxScope.required().setIsolation(TxIsolation.SERIALIZABLE))) {

      // Add in the outer transaction.
      var account = new AccountModel();
      account.insert();
      outerAccountId = account.id;
      assertThat(DB.find(AccountModel.class).findIds()).containsExactly(outerAccountId);

      outerTransaction.setNestedUseSavepoint();
      try (Transaction innerTransaction =
          DB.beginTransaction(TxScope.required().setIsolation(TxIsolation.SERIALIZABLE))) {
        new AccountModel().insert();
        // Assert that from within this inner transaction, we see the new account
        assertThat(DB.find(AccountModel.class).findCount()).isEqualTo(2);
        // Decide we don't really want this
        innerTransaction.rollback();
      }

      // We only see the outer data and not the inner as expected.
      assertThat(DB.find(AccountModel.class).findIds()).containsExactly(outerAccountId);
      // Keep this one.
      outerTransaction.commit();
    }

    // We still only see the outer data.
    assertThat(DB.find(AccountModel.class).findIds()).containsExactly(outerAccountId);
  }

  /** Batch mode is scoped to the transaction it is set in. */
  @Test
  public void transaction_innerBatchModeEnablesForInnerTransactionOnly() {
    try (Transaction outerTransaction =
        DB.beginTransaction(TxScope.required().setIsolation(TxIsolation.SERIALIZABLE))) {
      // Not set as expected.
      assertThat(outerTransaction.isBatchMode()).isFalse();

      try (Transaction innerTransaction =
          DB.beginTransaction(TxScope.required().setIsolation(TxIsolation.SERIALIZABLE))) {
        innerTransaction.setBatchMode(true);
        var account = new AccountModel();
        account.insert();
        // In batch mode we don't get IDs without a refresh.
        assertNull(account.id);

        innerTransaction.commit();
      }

      // Batch mode is off still in the outer transaction as expected.
      assertThat(outerTransaction.isBatchMode()).isFalse();

      // The batch IDs are available in the outer transaction.
      assertThat(DB.find(AccountModel.class).findCount()).isEqualTo(1);

      var account = new AccountModel();
      account.insert();
      // Outside of batch mode we now get IDs.
      assertNotNull(account.id);

      // Both are present in the DB.
      assertThat(DB.find(AccountModel.class).findCount()).isEqualTo(2);
    }
  }

  /*
   * Ebean has an L1 cache that affects Transactions.  Within a Transaction, Ebean's Persistence
   * Context returns the same Java object for the same logical DB data.
   *
   * The idea is to provide consistency in accessing database objects; however it runs counter to
   * the typical programming model in CiviForm where the lookups are assumed to be different
   * views of the same data.
   *
   * requriesNew() and savepoints change this behavior.
   *
   * <p>https://ebean.io/architecture/persistence-context
   */

  /** Basic example of the Transactional Persistence Context. */
  @Test
  public void transaction_sameObjectsInTransaction() {
    final String ORIGINAL_EMAIL = "original@email.com";
    final String UPDATED_EMAIL = "updated@email.com";
    var account = new AccountModel();
    account.setEmailAddress(ORIGINAL_EMAIL);
    account.insert();

    var accountId = account.id;

    // Look up the account.
    var outerAccount1 = database.find(AccountModel.class).setId(accountId).findOne();
    assertThat(outerAccount1.getEmailAddress()).isEqualTo(ORIGINAL_EMAIL);

    try (Transaction transaction =
        DB.beginTransaction(TxScope.required().setIsolation(TxIsolation.SERIALIZABLE))) {
      // Look up the account in a transaction.
      var innerAccount1 = database.find(AccountModel.class).setId(accountId).findOne();
      assertThat(innerAccount1.getEmailAddress()).isEqualTo(ORIGINAL_EMAIL);

      // Look it up again.
      var innerAccount2 = database.find(AccountModel.class).setId(accountId).findOne();
      // Update this objects email.
      innerAccount2.setEmailAddress(UPDATED_EMAIL);
      innerAccount2.save();

      // Note: Account1 is updated too unexpectedly.
      assertThat(innerAccount1.getEmailAddress()).isEqualTo(UPDATED_EMAIL);
      // Note: Account1 is actually the same object as Account2.
      assertThat(innerAccount1).isSameAs(innerAccount2);
      transaction.commit();
    }

    // The outer account is the same still though.
    assertThat(outerAccount1.getEmailAddress()).isEqualTo(ORIGINAL_EMAIL);

    // Outside a transaction they are separate objects.
    var outerAccount2 = database.find(AccountModel.class).setId(accountId).findOne();
    outerAccount2.setEmailAddress(UPDATED_EMAIL);
    outerAccount2.save();

    // Account1 is not the same object as Account2.
    assertThat(outerAccount1).isNotSameAs(outerAccount2);

    // Updating the second view doesn't change the first.
    assertThat(outerAccount1.getEmailAddress()).isEqualTo(ORIGINAL_EMAIL);
  }

  /**
   * One way around unintentional changes is to use savepoints and rollback the inner transaction.
   *
   * <p>In CiviForm though we don't use savepoints and rollbacks in user requests, so this would be
   * exceptional in our typical programming model.
   */
  @Test
  public void transaction_sameObjectsInTransaction_canRollback() {
    final String ORIGINAL_EMAIL = "original@email.com";
    final String UPDATED_EMAIL_1 = "updated1@email.com";
    final String UPDATED_EMAIL_2 = "updated2@email.com";
    var account = new AccountModel();
    account.setEmailAddress(ORIGINAL_EMAIL);
    account.insert();

    var accountId = account.id;

    // Look up the account outside of a transaction.
    var outerAccount = database.find(AccountModel.class).setId(accountId).findOne();
    assertThat(outerAccount.getEmailAddress()).isEqualTo(ORIGINAL_EMAIL);

    try (Transaction transaction =
        DB.beginTransaction(TxScope.required().setIsolation(TxIsolation.SERIALIZABLE))) {
      // Note: MUST have nested savepoints on.
      transaction.setNestedUseSavepoint();

      // Let's update the outer account to show how it interacts with the transaction data.
      outerAccount.setEmailAddress(UPDATED_EMAIL_1);
      outerAccount.save();

      // Look up the account in a transaction.
      var innerAccount = database.find(AccountModel.class).setId(accountId).findOne();
      // Transaction updated the data and we see that.
      assertThat(innerAccount.getEmailAddress()).isEqualTo(UPDATED_EMAIL_1);

      try (Transaction innerTransaction =
          DB.beginTransaction(TxScope.required().setIsolation(TxIsolation.SERIALIZABLE))) {
        // Look it up again in another transaction.
        var innerInnerAccount = database.find(AccountModel.class).setId(accountId).findOne();
        // Update this objects email in the inner transaction.
        innerInnerAccount.setEmailAddress(UPDATED_EMAIL_2);
        innerInnerAccount.save();

        // innerAccount1 is updated also.
        assertThat(innerAccount.getEmailAddress()).isEqualTo(UPDATED_EMAIL_2);
        // innerAccount1 is the same object as Account2.
        assertThat(innerAccount).isSameAs(innerInnerAccount);

        // Note: outerAccount is unchanged as it's a different object.
        assertThat(outerAccount.getEmailAddress()).isEqualTo(UPDATED_EMAIL_1);
        // Note: If we refresh though, it sees the same database data in the transaction.
        outerAccount.refresh();
        assertThat(outerAccount.getEmailAddress()).isEqualTo(UPDATED_EMAIL_2);

        // Rollback the transaction that changed the transaction object.
        innerTransaction.rollback();
        // Note: innerAccount1 object is still updated.
        assertThat(innerAccount.getEmailAddress()).isEqualTo(UPDATED_EMAIL_2);
        // Note: Until we refresh, let's refresh innerAccount2 to further exemplify they're the
        // same object, and the importance of refreshing in a rollback.
        innerInnerAccount.refresh();
        // Note: It's back to the value set in the outer transaction.
        assertThat(innerAccount.getEmailAddress()).isEqualTo(UPDATED_EMAIL_1);
      }

      // For good measure verify it's the same value in the outer transaction.
      assertThat(innerAccount.getEmailAddress()).isEqualTo(UPDATED_EMAIL_1);
      // Note: Let's try to keep everything done in the outer transaction.
      transaction.commit();
    }

    // Note: Because it's a different object, our outerAccount still reflects the refreshed data in
    // the inner transaction.
    assertThat(outerAccount.getEmailAddress()).isEqualTo(UPDATED_EMAIL_2);
    // Until we refresh it, then we get the commited changed in the outerTransaction.
    outerAccount.refresh();
    assertThat(outerAccount.getEmailAddress()).isEqualTo(UPDATED_EMAIL_1);
  }

  /**
   * Using requiresNew Scope uses a different transaction and as such gives a different object.
   *
   * <p>In CiviForm though we don't use different simultaneous transactions, so this would be
   * exceptional in our typical programming model.
   */
  @Test
  public void transaction_sameObjectsInTransaction_requiresNew_givesDifferentObjects() {
    final String ORIGINAL_EMAIL = "original@email.com";
    final String UPDATED_EMAIL = "updated@email.com";
    var account = new AccountModel();
    account.setEmailAddress(ORIGINAL_EMAIL);
    account.insert();

    var accountId = account.id;

    var outerAccount = database.find(AccountModel.class).setId(accountId).findOne();
    assertThat(outerAccount.getEmailAddress()).isEqualTo(ORIGINAL_EMAIL);

    try (Transaction transaction =
        DB.beginTransaction(TxScope.required().setIsolation(TxIsolation.SERIALIZABLE))) {

      // Look up the account in a transaction.
      var innerAccount = database.find(AccountModel.class).setId(accountId).findOne();
      assertThat(innerAccount.getEmailAddress()).isEqualTo(ORIGINAL_EMAIL);

      // Note: Creating a separate transaction scope.
      try (Transaction innerTransaction =
          DB.beginTransaction(TxScope.requiresNew().setIsolation(TxIsolation.SERIALIZABLE))) {
        // Look it up again.
        var innerInnerAccount = database.find(AccountModel.class).setId(accountId).findOne();
        // Update this objects email.
        innerInnerAccount.setEmailAddress(UPDATED_EMAIL);
        innerInnerAccount.save();
        innerTransaction.commit();

        // Note: innerAccount is NOT updated.
        assertThat(innerAccount.getEmailAddress()).isEqualTo(ORIGINAL_EMAIL);
        // Note:  innerAccount is NOT the same object as Account2.
        assertThat(innerAccount).isNotSameAs(innerInnerAccount);
      }

      // And because they're different transactions, they see different views of the database.
      innerAccount.refresh();
      // innerAccount1 is unchanged relative to its transaction.
      assertThat(innerAccount.getEmailAddress()).isEqualTo(ORIGINAL_EMAIL);
    }
  }

  /**
   * However, in comparison to the above test, for some unknown reason the above doesn't work if you
   * also use savepoints.
   */
  @Test
  public void transaction_sameObjectsInTransaction_requiresNewAndSavepoints_givesSameObjects() {
    final String ORIGINAL_EMAIL = "original@email.com";
    final String UPDATED_EMAIL = "updated@email.com";
    var account = new AccountModel();
    account.setEmailAddress(ORIGINAL_EMAIL);
    account.insert();

    var accountId = account.id;

    // Look up the account.
    var outerAccount = database.find(AccountModel.class).setId(accountId).findOne();
    assertThat(outerAccount.getEmailAddress()).isEqualTo(ORIGINAL_EMAIL);

    try (Transaction transaction =
        DB.beginTransaction(TxScope.required().setIsolation(TxIsolation.SERIALIZABLE))) {
      // Note: Using savepoints for some reason changes the persistence modeling of using a separate
      // transaction.
      transaction.setNestedUseSavepoint();

      // Look up the account in a transaction.
      var innerAccount = database.find(AccountModel.class).setId(accountId).findOne();
      assertThat(innerAccount.getEmailAddress()).isEqualTo(ORIGINAL_EMAIL);

      // Note: Creating a separate transaction.
      try (Transaction innerTransaction =
          DB.beginTransaction(TxScope.requiresNew().setIsolation(TxIsolation.SERIALIZABLE))) {
        // Look it up again.
        var innerInnerAccount = database.find(AccountModel.class).setId(accountId).findOne();
        // Update this objects email.
        innerInnerAccount.setEmailAddress(UPDATED_EMAIL);

        // Note: innerAccount is updated unexpectedly.
        assertThat(innerAccount.getEmailAddress()).isEqualTo(UPDATED_EMAIL);
        // Note: innerAccount is the same object as innerInnerAccount unexpectedly.
        assertThat(innerAccount).isSameAs(innerInnerAccount);
      }
    }
  }

  // **** Async tests

  /* Async
   *
   * Async code doesn't work with our Transaction setup.
   *
   * The current transaction is maintained in thread-local storage, however
   * Async calls create a new thread with its own storage.
   *
   * We can explicitly specify the transaction in the Ebean queries though.
   * This is likely onerous as a broad approach but specific needs may allow
   * for it more cleanly.
   */
  @Test
  @Parameters({"false", "true"})
  public void async_mustExplicitlyManageTransaction(boolean setInnerTransaction) {
    try (Transaction _ =
        DB.beginTransaction(TxScope.required().setIsolation(TxIsolation.SERIALIZABLE))) {
      // While we could have named the above transaction, this shows how to
      // get the current one.
      Transaction outerTransaction = Transaction.current();
      // Insert a few just to reduce confusion with the 1 added in the Async
      // call.
      new AccountModel().insert();
      new AccountModel().insert();

      int beforeCount = database.find(AccountModel.class).findCount();
      assertThat(beforeCount).isEqualTo(2);

      // Using the current transaction in the Async code will reveal the outer
      // code's updates to the inner, and vice versa.
      int innerCount =
          supplyAsync(
                  () -> {
                    Query<AccountModel> query = database.find(AccountModel.class);
                    if (setInnerTransaction) {
                      new AccountModel().insert(outerTransaction);
                      query = query.usingTransaction(outerTransaction);
                    } else {
                      // The insert will have its own transaction.
                      new AccountModel().insert();
                    }
                    return query.findCount();
                  })
              .toCompletableFuture()
              .join();

      // How many did the Async code see?
      assertThat(innerCount).isEqualTo(setInnerTransaction ? 3 : 1);
      // How may does the outer transaction see?
      int afterCount = database.find(AccountModel.class).findCount();
      assertThat(afterCount).isEqualTo(setInnerTransaction ? 3 : 2);
    }
  }

  /**
   * We can explicitly set transactions on queries, however their interaction with ebean is subtle.
   * When a transaction is set it only works for the initial query and are not persisted for lazy
   * loaded ones such as Many2Many relations. There is no way to force the transaction it uses.
   *
   * <p>We might set a transaction explicitly to handle that they are not automatically passed
   * through async code; however there are hidden consequences based on the operations done in the
   * async code.
   */
  @Test
  @Parameters({"false", "true"})
  public void async_settingTransactionWorksForLookupsButNotForLazyLoad(boolean resolveInAsync) {
    // A version with no questions, committed before the transaction opens.
    VersionModel version = new VersionModel(LifecycleStage.DRAFT);
    version.save();
    long versionId = version.id;

    // Record the value from the async code to check after.
    // If we assert in the async the error will not attribute correctly.
    AtomicInteger countViaLookupInAsyncWithTransaction = new AtomicInteger(-1);

    try (Transaction _ =
        DB.beginTransaction(TxScope.required().setIsolation(TxIsolation.SERIALIZABLE))) {
      Transaction outerTransaction = Transaction.current();

      // Attach a question to the version. Ebean writes the versions_questions row from the
      // question side. It is uncommitted, so only this transaction can see it.
      QuestionModel question = new QuestionModel(QUESTION_DEFINITION);
      question.addVersion(version);
      question.save();

      // This transaction sees the question.
      int questionCount =
          database.find(QuestionModel.class).where().eq("versions.id", versionId).findCount();
      assertThat(questionCount).isEqualTo(1);

      VersionModel versionFromAsync =
          supplyAsync(
                  () -> {
                    // Binding to the transaction will see the question
                    // inside async code.
                    countViaLookupInAsyncWithTransaction.set(
                        database
                            .find(QuestionModel.class)
                            .usingTransaction(outerTransaction)
                            .where()
                            .eq("versions.id", versionId)
                            .findCount());

                    // Using the same transaction fetch the VersionModel side
                    // of the relation.
                    VersionModel versionWithTransactionSet =
                        database
                            .find(VersionModel.class)
                            .usingTransaction(outerTransaction)
                            .where()
                            .idEq(versionId)
                            .findOne();

                    // The value for getQuestions will depend on the
                    // transaction context it is evaluated, and cached, in.
                    // In the async work it will not see the question as
                    // there is no implicit transaction.
                    if (resolveInAsync) {
                      versionWithTransactionSet.getQuestions();
                    }

                    return versionWithTransactionSet;
                  })
              .toCompletableFuture()
              .join();

      // Inside the Async with the transaction we saw the uncommited question.
      assertThat(countViaLookupInAsyncWithTransaction.get()).isEqualTo(1);

      // The lazy loaded value we get on the returned VersionModel depends on
      // when it was evaluated. Inside the async it had no implicit transaction and
      // did not see the question. Outside it implicitly has the transaction
      // and now sees it.
      assertThat(versionFromAsync.getQuestions().size()).isEqualTo(resolveInAsync ? 0 : 1);

      // We can refresh and re-evaluate the cached value to what we expect.
      // There are two ways to go about this.  .refresh triggers an immediate
      // update. The following unsets the cached value and defers evaluation
      // until its needed, if at all.
      BeanState beanState = DB.beanState(versionFromAsync);
      beanState.setPropertyLoaded("questions", false);
      assertThat(versionFromAsync.getQuestions()).hasSize(1);
    }
  }

  /* Collection fetch tests.
   *
   * Ebean invokes @PostLoad once per bean, on that bean's FIRST result-set row. Later rows find
   * the bean already in the Persistence Context and skip the callback.
   *
   * <p>That is invisible for scalar columns, which repeat identically on every row. It matters
   * for a to-many fetched as a SQL join, because such a collection is spread across one row per
   * element and is still being filled after the callback has run. A @PostLoad that copies the
   * collection therefore copies a partial one.
   *
   * <p>ProgramModel does exactly that: loadProgramDefinition() builds an immutable
   * ProgramDefinition, including a copy of the categories. The entity ends up correct while the
   * copy held inside it does not.
   */

  /** Inserts a program with several categories and returns its id. */
  private long insertProgramWithCategories() {
    return insertProgramWithCategories("invariant-program");
  }

  /** Inserts a named program with several categories and returns its id. */
  private long insertProgramWithCategories(String adminName) {
    ImmutableList<CategoryModel> categories =
        ImmutableList.of(
            resourceCreator.insertCategory(ImmutableMap.of(Locale.US, "Food")),
            resourceCreator.insertCategory(ImmutableMap.of(Locale.US, "Family")),
            resourceCreator.insertCategory(ImmutableMap.of(Locale.US, "Health")));
    return ProgramBuilder.newActiveProgram(adminName).withCategories(categories).build().id;
  }

  /**
   * queriesSinceLastCount() only sees ORM queries. Raw SQL reads, even labelled ones, and all
   * writes are invisible to it, so query count assertions undercount code paths that use them.
   */
  @Test
  public void queryMetrics_onlyCountOrmQueries() {
    new AccountModel().insert();
    queriesSinceLastCount();

    database.find(AccountModel.class).findList();
    assertThat(queriesSinceLastCount()).isEqualTo(1);

    database.sqlQuery("SELECT id FROM accounts").findList();
    assertThat(queriesSinceLastCount()).isEqualTo(0);

    // A label does not opt a raw SQL query into the metrics.
    database.sqlQuery("SELECT id FROM accounts").setLabel("labelled").findList();
    assertThat(queriesSinceLastCount()).isEqualTo(0);

    database.sqlQuery("SELECT count(*) FROM accounts").mapToScalar(Long.class).findOne();
    assertThat(queriesSinceLastCount()).isEqualTo(0);

    database.sqlUpdate("UPDATE accounts SET email_address = 'a@b.com'").execute();
    assertThat(queriesSinceLastCount()).isEqualTo(0);

    new AccountModel().insert();
    assertThat(queriesSinceLastCount()).isEqualTo(0);
  }

  @Test
  public void collectionFetch_joinTruncatesThePostLoadCopyUntilReloaded() {
    long programId = insertProgramWithCategories();

    // Fetched as a SQL join, so the collection arrives one element per row.
    ProgramModel program =
        database
            .find(ProgramModel.class)
            .fetch("categories")
            .where()
            .eq("id", programId)
            .findList()
            .getFirst();

    // The entity itself is never wrong. Every join row is appended to the bean's collection, and
    // by the time findList() returns they have all been read.
    assertThat(program.getCategories()).hasSize(3);

    // The copy taken during @PostLoad is wrong. The callback ran on the first join row, when a
    // single category had been read, and rows two and three did not re-fire it.
    assertThat(program.getProgramDefinition().categories()).hasSize(1);

    // Rerunning the PostLoad method after the query completes corrects the data copy.
    program.loadProgramDefinition();
    assertThat(program.getProgramDefinition().categories()).hasSize(3);
    assertThat(program.getProgramDefinition().categories())
        .containsExactlyInAnyOrderElementsOf(program.getCategories());
  }

  @Test
  public void collectionFetch_queryJoinIsNotTruncated() {
    long programId = insertProgramWithCategories();

    ProgramModel program =
        database
            .find(ProgramModel.class)
            .fetch("categories", FetchConfig.ofQuery())
            .where()
            .eq("id", programId)
            .findList()
            .getFirst();

    // A query join leaves the collection an unloaded proxy when @PostLoad runs, so reading it
    // there forces a complete load and no rebuild is needed. The cost is that the load happens
    // per bean while the main result set is still open, rather than as one batched secondary
    // query.
    assertThat(program.getProgramDefinition().categories()).hasSize(3);
  }

  @Test
  public void collectionFetch_lazyCollectionIsNotTruncated() {
    long programId = insertProgramWithCategories();

    // No fetch at all, so categories is left as an unloaded proxy.
    ProgramModel program =
        database.find(ProgramModel.class).where().eq("id", programId).findList().getFirst();

    // Reading that proxy inside @PostLoad forces it to load in full, exactly as the query join
    // does. Only a SQL joined collection escapes this, because it is not a proxy at all, just a
    // real list that is still being filled.
    assertThat(program.getProgramDefinition().categories()).hasSize(3);
  }

  @Test
  public void collectionFetch_onlyTheJoinAvoidsAQueryPerBean() {
    int programCount = 3;
    for (int i = 0; i < programCount; i++) {
      insertProgramWithCategories("invariant-program-" + i);
    }
    queriesSinceLastCount();

    database.find(ProgramModel.class).fetch("categories").findList();
    long joinQueries = queriesSinceLastCount();

    database.find(ProgramModel.class).fetch("categories", FetchConfig.ofQuery()).findList();
    long queryJoinQueries = queriesSinceLastCount();

    database.find(ProgramModel.class).findList();
    long lazyQueries = queriesSinceLastCount();

    // The join reads every program and every category in one statement.
    assertThat(joinQueries).isEqualTo(1);

    // The other two each pay one extra query per bean. @PostLoad touches the proxy while the
    // main result set is still being read, so the load buffer holds only the bean just read and
    // Ebean never gets to batch them. Notably ofQuery asks for a single batched secondary query
    // and does not get one, making it indistinguishable from lazy loading here.
    assertThat(queryJoinQueries).isEqualTo(1 + programCount);
    assertThat(lazyQueries).isEqualTo(1 + programCount);
  }
}
