{
 "title": "CiviForm server",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "General metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests per minute (by path)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (path) (rate(http_requests_total{}[1m]))",
     "legendFormat": "{{controller}}.{{method}} {{path}} {{status}}"
    }
   ]
  },
  {
   "title": "Request latency p50 (by action)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum without(instance,Verb,Status,Path,job) ( rate(requests_latency_seconds_bucket{}[5m])) )",
     "legendFormat": "{{Controller}}.{{RouteActionMethod}}"
    }
   ]
  },
  {
   "title": "Request latency p90 (by action)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum without(instance,Verb,Status,Path,job) ( rate(requests_latency_seconds_bucket{}[5m])) )",
     "legendFormat": "{{Controller}}.{{RouteActionMethod}}"
    }
   ]
  },
  {
   "title": "Request latency p99 (by action)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum without(instance,Verb,Status,Path,job) ( rate(requests_latency_seconds_bucket{}[5m])) )",
     "legendFormat": "{{Controller}}.{{RouteActionMethod}}"
    }
   ]
  },
  {
   "title": "Requests per minute (by action)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by (controller,method) (rate(http_requests_total{}[1m]))",
     "legendFormat": "{{controller}}.{{method}}"
    }
   ]
  },
  {
   "title": "Client errors per minute (by action and status)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum by (controller,method,status) (rate(http_requests_total{status=~\"404|401|400\"}[1m]))",
     "legendFormat": "{{controller}}.{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Server errors per minute (by action)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum by (controller,method) (rate(http_requests_total{status=~\"500\"}[1m]))",
     "legendFormat": "{{controller}}.{{method}}"
    }
   ]
  },
  { "title": "Database metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Total queries per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    { "expr": "rate(ebean_queries_total[1m])", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Total queries per minute (excluding durable job runner)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    { "expr": "rate(ebean_queries_total[1m])", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Average Query Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(ebean_queries_total_latency_micros[5m]) \n/ \nrate(ebean_queries_total[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Mean latency micros per minute (excluding durable jobs runner)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg_over_time(ebean_queries_mean_latency_micros{}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Max latency micros per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max_over_time(ebean_queries_max_latency_micros{}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Max latency micros per minute (excluding durable jobs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max_over_time(ebean_queries_max_latency_micros{}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total latency micros per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(ebean_queries_total_latency_micros{}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total latency micros per minute (excluding durable jobs runner)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(ebean_queries_total_latency_micros{}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Email Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Email Send Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "rate(email_send_time_seconds_sum{instance=\"0.0.0.0:9000\"}[5m])/rate(email_send_time_seconds_count{instance=\"0.0.0.0:9000\"}[5m])",
     "legendFormat": "Average Email Send Time"
    }
   ]
  },
  {
   "title": "Successful Email Sends Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "expr": "rate(email_send_total{status=\"200\"}[1m])",
     "legendFormat": "200 Status"
    }
   ]
  },
  {
   "title": "Failed Email Sends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "increase(email_fail_total{instance=\"0.0.0.0:9000\"}[$__interval])",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}