#! /usr/bin/env bash

source "cloud/azure/bin/lib.sh"

set -e

while getopts g:s: flag
do
  case "${flag}" in
    g) resource_group="${OPTARG}";;
    s) staging_hostname="${OPTARG}";;
    *) out::error "Unexpected getopts value ${flag}";;
  esac
done


readonly APP_NAME="$(azure::get_app_name "${resource_group}")"
readonly CANARY_URL="$(azure::get_canary_url "${resource_group}" "${APP_NAME}")"
readonly PRIMARY_URL="$(azure::get_primary_url "${resource_group}" "${APP_NAME}")"

azure::slot_setting "canary" "${APP_NAME}" "BASE_URL" "https://${CANARY_URL}" "${resource_group}"
azure::slot_setting "primary" "${APP_NAME}" "BASE_URL" "https://${staging_hostname}" "${resource_group}" 

# If the environment is staging, then we should set the staging hostname of the canary instance to its app service URL
# so that it matches the base URL and is also treated as a staging instance
azure::slot_setting "canary" "${APP_NAME}" "STAGING_HOSTNAME" "${CANARY_URL}" "${resource_group}"
azure::slot_setting "primary" "${APP_NAME}" "STAGING_HOSTNAME" "${staging_hostname}" "${resource_group}"

