#! /usr/bin/env bash

set -e

readonly TF_VAR_FILE="cloud/deploys/staging_azure/staging.tfvars"
readonly TEMPLATE_DIR="cloud/azure/templates/azure_saml_ses"
readonly VARS_FILENAME="cloud/deploys/staging_azure/staging_azure_backend_vars"

# Apply any infra changes with terraform. This will unset the slot settings, so we'll
# set them again after we run terraform apply
# TODO: get terraform to ignore the slot settings
terraform \
  -chdir="${TEMPLATE_DIR}" \
  init \
  -backend-config="${VARS_FILENAME}"

terraform \
  -chdir="${TEMPLATE_DIR}" \
  apply \
  -var-file="${TF_VAR_FILE}"

cloud/deploys/dev_azure/configure-slot-settings -g "${AZURE_RESOURCE_GROUP}" "${STAGING_HOSTNAME}"

cloud/azure/bin/deploy
