#! /usr/bin/env bash

# DOC: Runs creates the azure staging environment

set -e

readonly THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE}")")"
readonly PROJECT_BASE_DIR="$(realpath "${THIS_DIR}/../../../")"

source "${PROJECT_BASE_DIR}/cloud/azure/bin/lib.sh"

readonly TF_VAR_FILE="${THIS_DIR}/staging.tfvars"
readonly TEMPLATE_DIR="${PROJECT_BASE_DIR}/cloud/azure/templates/azure_saml_ses"
readonly VARS_FILENAME="${THIS_DIR}/staging_azure_backend_vars"
readonly RESOURCE_GROUP_NAME="tfstate"

readonly SSH_KEY_FILE="${HOME}/.ssh/bastion"

if ! [[ -f "${SSH_KEY_FILE}" ]]; then
  echo "Creating a new ssh key"
  ssh-keygen -t rsa -b 4096 -f "${SSH_KEY_FILE}"
fi

key_vault::assign_secrets_officer_role_to_user "staging-kv-rg"
storage::assign_storage_blob_data_contributor_role_to_user "${RESOURCE_GROUP_NAME}"

cloud/azure/bin/setup_tf_shared_state "${VARS_FILENAME}"

terraform \
  -chdir="${TEMPLATE_DIR}" \
  init \
  -backend-config="${VARS_FILENAME}"

terraform \
  -chdir="${TEMPLATE_DIR}" \
  apply \
  -var-file="${TF_VAR_FILE}"
