# Builds on docker-compose.yml
version: '3.4'

services:
  localstack:
    ports:
      - 6645:4566

  azurite:
    ports:
      - 10000:10000

  civiform:
    image: civiform-dev
    restart: always
    links:
      - 'db:database'
      - 'dev-oidc'
    ports:
      - 9999:9000
    environment:
      - CIVIFORM_APPLICANT_IDP=idcs
      - APPLICANT_OIDC_PROVIDER_LOGOUT=true
      - IDCS_CLIENT_ID=idcs-fake-oidc-client
      - IDCS_SECRET=idcs-fake-oidc-secret
      - IDCS_DISCOVERY_URI=http://dev-oidc:3390/.well-known/openid-configuration
      - DB_JDBC_STRING=jdbc:postgresql://database:5432/postgres
      - BASE_URL=http://civiform:9000
      - LOCALSTACK_URL=http://localstack:4566
      - CIVIFORM_TIME_ZONE_ID
      # The default value is true, we set it to false here because we do not know
      # the IP address that will be used to call the API in the browser tests.
      - CIVIFORM_API_KEYS_BAN_GLOBAL_SUBNET=false
    command: ~run -Dconfig.file=conf/application.dev-browser-tests.conf
