# Builds on docker-compose.yml
version: "3.4"

services:
  localstack:
    ports:
      - 6645:4566

  azurite:
    ports:
      - 10000:10000

  fake-idcs:
    image: docker.io/civiform/oidc-provider:latest
    restart: always
    ports:
      - 8033:3380

  civiform:
    image: civiform
    restart: always
    links:
      - "db:database"
      - "fake-idcs"
    ports:
      - 9999:9000
    environment:
      - IDCS_CLIENT_ID=foo
      - IDCS_SECRET=bar
      - IDCS_DISCOVERY_URI=http://fake-idcs:3380/.well-known/openid-configuration
      - DB_JDBC_STRING=jdbc:postgresql://database:5432/postgres
      - BASE_URL=http://civiform:9000
      - JAVA_TIME_ZONE_ID
    command: ~run -Dconfig.file=conf/application.dev.conf
