# Builds on browser-test-compose.yml
# Mount code for hot reloading and cache for faster compile in dev mode.
version: '3.4'
services:
  civiform:
    image: civiform-dev
    build: .. # build the civiform-dev image.
    volumes:
      - ./server:/usr/src/server
      - target:/usr/src/server/target
      - node_modules-data:/usr/src/server/node_modules
      - project-data:/usr/src/server/project
      - coursier-data:/root/.cache/coursier
      - sbt-data:/root/.sbt
      - ivy2-data:/root/.ivy2
      - m2-data:/root/.m2
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - 9100:9000
      - 9457:8457
    command: -jvm-debug "*:9457" ~run -Dconfig.file=conf/application.dev.conf

volumes:
  node_modules-data:
    driver: local
  project-data:
    driver: local
  coursier-data:
    driver: local
  sbt-data:
    driver: local
  ivy2-data:
    driver: local
  m2-data:
    driver: local
  target:
    driver: local
