# Builds on docker-compose.yml
version: '3.4'

services:
  db:
    volumes:
      - ./browser-test/custom-postgres.conf:/etc/postgresql/postgresql.conf
    command: -c 'config_file=/etc/postgresql/postgresql.conf'

  localstack:
    ports:
      - 6645:4566

  azurite:
    ports:
      - 10000:10000

  civiform:
    image: civiform-dev
    restart: always
    links:
      - 'db:database'
      - 'dev-oidc'
    ports:
      - 9999:9000
    environment:
      - CIVIFORM_APPLICANT_IDP=idcs
      - IDCS_CLIENT_ID=idcs-fake-oidc-client
      - IDCS_SECRET=idcs-fake-oidc-secret
      - IDCS_DISCOVERY_URI=http://dev-oidc:3390/.well-known/openid-configuration
      - APPLICANT_REGISTER_URI=http://dev-oidc:3390/
      - CIVIFORM_ADMIN_IDP=adfs
      - DB_JDBC_STRING=jdbc:postgresql://database:5432/postgres
      - BASE_URL=${BASE_URL:-http://civiform:9000}
      - LOCALSTACK_URL=http://localhost.localstack.cloud:4566
      - CIVIFORM_TIME_ZONE_ID
    command: ~runBrowserTestsServer
    entrypoint: ./entrypoint.sh -jvm-debug "0.0.0.0:9457"
