# Builds on docker-compose.yml
version: '3.4'

services:
  localstack:
    ports:
      - 6645:4566

  azurite:
    ports:
      - 10000:10000

  fake-idcs:
    image: docker.io/civiform/oidc-provider:latest
    restart: always
    ports:
      - 8033:3380

  civiform:
    image: civiform-dev
    restart: always
    links:
      - 'db:database'
      - 'fake-idcs'
    ports:
      - 9999:9000
    environment:
      - IDCS_CLIENT_ID=foo
      - IDCS_SECRET=bar
      - IDCS_DISCOVERY_URI=http://fake-idcs:3380/.well-known/openid-configuration
      - DB_JDBC_STRING=jdbc:postgresql://database:5432/postgres
      - BASE_URL=http://civiform:9000
      - CIVIFORM_TIME_ZONE_ID
      # The default value is true, we set it to false here because we do not know
      # the IP address that will be used to call the API in the browser tests.
      - CIVIFORM_API_KEYS_BAN_GLOBAL_SUBNET=false
    command: ~run -Dconfig.file=conf/application.dev.conf
