services:
  env-var-docs:
    image: python:3.14.6-slim@sha256:7bec7ddcddeff7975d6ba9b4be7dd6f6b2f55e7491539145e2978f7f97ce9144
    container_name: civiform-vars-parser-package
    tty: true
    entrypoint: /bin/bash
    working_dir: /code
    volumes:
      - ../:/code
    environment:
      - PIP_ROOT_USER_ACTION=ignore
      - PIP_DISABLE_PIP_VERSION_CHECK=true
