services:
  env-var-docs:
    image: python:3.14.7-slim@sha256:51dafde81dbdb6ebde285137a295cf18a47ca95234fe388a343719cb97305b3d
    container_name: civiform-vars-parser-package
    tty: true
    entrypoint: /bin/bash
    working_dir: /code
    volumes:
      - ../:/code
    environment:
      - PIP_ROOT_USER_ACTION=ignore
      - PIP_DISABLE_PIP_VERSION_CHECK=true
