services:
  env-var-docs:
    image: python:3.14.3-slim@sha256:9006fc63e3eaedc00ebc81193c99528575a2f9b9e3fb36d95e94814c23f31f47
    container_name: civiform-vars-parser-package
    tty: true
    entrypoint: /bin/bash
    working_dir: /code
    volumes:
      - ../:/code
    environment:
      - PIP_ROOT_USER_ACTION=ignore
      - PIP_DISABLE_PIP_VERSION_CHECK=true
