// Generated by Grafana k6 Studio (1.13.1) on 2026-06-25T13:14:03.031Z
//
// Use Case: A guest applying to the Minimal Sample Program

import { browser } from "k6/browser";

export const options = {
  scenarios: {
    default: {
      executor: "shared-iterations",
      options: { browser: { type: "chromium" } },
      // Simultaneous users
      vus: 1,
      // Total runs across all users
      iterations: 10,
      // max duration of the test, defaults to 10m
      maxDuration: "30m",
    },
  },

  // Timing alert criteria
  // https://grafana.com/docs/k6/latest/using-k6/thresholds/
  // 
  // The 'name's here are set in the page.on() handler below.
  // browser_http_req_duration is a built in metric on request latency
  thresholds: {
    // Edit actions should complete within 60ms on mean average and 100ms 95% of the time.
    "browser_http_req_duration{name:block_edit}": ['avg < 60', 'p(95) < 100'],
    "browser_http_req_duration{name:program_submit}": ['avg < 65', 'p(95) < 90']
  }
};

export default async function () {
  const page = await browser.newPage();

  // Connect urls with metric tags to use in the thresholds.
  page.on("metric", (metric) => {
    metric.tag({
      name: "block_edit", matches: [{ url: /\/programs\/\d+\/blocks\/\d+\/edit$/ }],
    });
    metric.tag({
      name: "program_submit", matches: [{ url: /\/programs\/\d+\/submit$/ }],
    });
  });

  try {
    await page.goto("http://civiform:9000/programs");

    await Promise.all([
      page.waitForNavigation(),
      page
        .getByRole("link", {
          name: "View and apply to Minimal Sample Program",
          exact: true,
        })
        .click(),
    ]);

    await Promise.all([
      page.waitForNavigation(),
      page
        .getByRole("button", {
          name: "Start application as a guest",
          exact: true,
        })
        .click(),
    ]);

    await page
      .getByRole("textbox", { name: "First name", exact: true })
      .fill("guest");

    await page
      .getByRole("textbox", { name: "Last name", exact: true })
      .fill("guest");

    await Promise.all([
      page.waitForNavigation(),
      page.getByRole("button", { name: "Continue", exact: true }).click(),
    ]);

    await Promise.all([
      page.waitForNavigation(),
      page.getByRole("link", { name: "Edit", exact: true }).click(),
    ]);

    await Promise.all([
      page.waitForNavigation(),
      page.getByRole("button", { name: "Continue", exact: true }).click(),
    ]);

    await Promise.all([
      page.waitForNavigation(),
      page
        .getByRole("button", { name: "Submit application", exact: true })
        .click(),
    ]);

    await page
      .getByRole("button", { name: "Back to homepage", exact: true })
      .click();

  } finally {
    await page?.close();
  }
}
