// Generated by Grafana k6 Studio (1.13.1) on 2026-06-25T13:14:03.031Z

import { browser } from "k6/browser";

export const options = {
  scenarios: {
    default: {
      executor: "shared-iterations",
      options: { browser: { type: "chromium" } },
      // Simultaneous users
      vus: 1,
      // Total runs across all users
      iterations: 10,
      // max duration of the test, defaults to 10m
      maxDuration: "30m",
    },
  },

  // Timing alert criteria
  // https://grafana.com/docs/k6/latest/using-k6/thresholds/
  thresholds: {
    // Edit actions should complete within 60ms on mean average and 100ms 95% of the time.
    "browser_http_req_duration{name:block_edit}": ['avg < 60', 'p(95) < 100'],
    "browser_http_req_duration{name:program_submit}": ['avg < 65', 'p(95) < 90']
  }
};

export default async function () {
  const page = await browser.newPage();

  // Connect urls with metric tags to use in the thresholds.
  page.on("metric", (metric) => {
    metric.tag({
      name: "block_edit", matches: [{ url: /\/programs\/\d+\/blocks\/\d+\/edit$/ }],
    });
    metric.tag({
      name: "program_submit", matches: [{ url: /\/programs\/\d+\/submit$/ }],
    });
  });

  try {
    await page.goto("http://civiform:9000/programs");

    await Promise.all([
      page.waitForNavigation(),
      page
        .getByRole("link", {
          name: "View and apply to Minimal Sample Program",
          exact: true,
        })
        .click(),
    ]);

    await Promise.all([
      page.waitForNavigation(),
      page
        .getByRole("button", {
          name: "Start application as a guest",
          exact: true,
        })
        .click(),
    ]);

    await page
      .getByRole("textbox", { name: "First name", exact: true })
      .fill("guest");

    await page
      .getByRole("textbox", { name: "Last name", exact: true })
      .fill("guest");

    await Promise.all([
      page.waitForNavigation(),
      page.getByRole("button", { name: "Continue", exact: true }).click(),
    ]);

    await Promise.all([
      page.waitForNavigation(),
      page.getByRole("link", { name: "Edit", exact: true }).click(),
    ]);

    await Promise.all([
      page.waitForNavigation(),
      page.getByRole("button", { name: "Continue", exact: true }).click(),
    ]);

    await Promise.all([
      page.waitForNavigation(),
      page
        .getByRole("button", { name: "Submit application", exact: true })
        .click(),
    ]);

    await page
      .getByRole("button", { name: "Back to homepage", exact: true })
      .click();

    await Promise.all([
      page.waitForNavigation(),
      page
        .getByRole("link", { name: "Continue without an account", exact: true })
        .click(),
    ]);

    await Promise.all([
      page.waitForNavigation(),
      page
        .getByRole("link", {
          name: "View and apply to Comprehensive Sample Program",
          exact: true,
        })
        .click(),
    ]);

    await Promise.all([
      page.waitForNavigation(),
      page
        .getByRole("button", {
          name: "Start application as a guest",
          exact: true,
        })
        .click(),
    ]);

    await page
      .getByRole("textbox", { name: "Address", exact: true })
      .fill("1 pine st");

    await page
      .getByRole("textbox", { name: "City", exact: true })
      .fill("seattle");

    await page
      .getByRole("combobox", { name: "State", exact: true })
      .selectOption("WA");

    await page
      .getByRole("textbox", { name: "ZIP Code", exact: true })
      .fill("90212");

    await page.locator("div:nth-of-type(2) > label:nth-child(2)").click();

    await page
      .getByRole("textbox", {
        name: "How much should a scoop of ice cream cost?",
        exact: true,
      })
      .fill("3");

    await page
      .getByRole("combobox", { name: "Month", exact: true })
      .selectOption("3");

    await page.getByRole("textbox", { name: "Day", exact: true }).fill("1`");

    await page.getByRole("textbox", { name: "Day", exact: true }).fill("11");

    await page.getByRole("textbox", { name: "Year", exact: true }).fill("1923");

    await page
      .getByRole("combobox", {
        name: "Select your favorite ice cream flavor from the following",
        exact: true,
      })
      .selectOption("2");

    await page
      .getByRole("textbox", { name: "what is your phone number", exact: true })
      .fill("(206) 564-5645");

    await Promise.all([
      page.waitForNavigation(),
      page.getByRole("button", { name: "Continue", exact: true }).click(),
    ]);

    await Promise.all([
      page.waitForNavigation(),
      page
        .getByRole("link", {
          name: "City of TestCity Logo TestCity CiviForm",
          exact: true,
        })
        .click(),
    ]);

    await Promise.all([
      page.waitForNavigation(),
      page
        .getByRole("link", {
          name: "View and apply to Comprehensive Sample Program",
          exact: true,
        })
        .click(),
    ]);

    await Promise.all([
      page.waitForNavigation(),
      page
        .getByRole("link", {
          name: "City of TestCity Logo TestCity CiviForm",
          exact: true,
        })
        .click(),
    ]);

    await Promise.all([
      page.waitForNavigation(),
      page
        .getByRole("link", {
          name: "View and apply to Comprehensive Sample Program",
          exact: true,
        })
        .click(),
    ]);

    await Promise.all([
      page.waitForNavigation(),
      page
        .getByRole("button", { name: "Review and submit", exact: true })
        .click(),
    ]);

    await Promise.all([
      page.waitForNavigation(),
      page.locator("li:nth-of-type(4) .usa-button").click(),
    ]);

    await page.locator("div:nth-of-type(3) > div > label").click();

    await Promise.all([
      page.waitForNavigation(),
      page.getByRole("button", { name: "Continue", exact: true }).click(),
    ]);

    await page
      .getByRole("combobox", { name: "Month", exact: true })
      .selectOption("3");

    await page.getByRole("textbox", { name: "Day", exact: true }).fill("12");

    await page.getByRole("textbox", { name: "Year", exact: true }).fill("1945");

    await Promise.all([
      page.waitForNavigation(),
      page.getByRole("button", { name: "Continue", exact: true }).click(),
    ]);

    await Promise.all([
      page.waitForNavigation(),
      page.getByRole("button", { name: "Continue", exact: true }).click(),
    ]);

    await Promise.all([
      page.waitForNavigation(),
      page.getByRole("link", { name: "Continue", exact: true }).click(),
    ]);

    await Promise.all([
      page.waitForNavigation(),
      page.getByRole("button", { name: "Continue", exact: true }).click(),
    ]);

    await page
      .getByRole("textbox", { name: "What is your email?", exact: true })
      .fill("sdf@dsf.com");

    await page
      .getByRole("textbox", {
        name: "What is your driver\\'s license ID?",
        exact: true,
      })
      .fill("23432432");

    await page
      .getByRole("spinbutton", {
        name: "How many pets do you have?",
        exact: true,
      })
      .fill("2");

    await page
      .getByRole("textbox", {
        name: "What is your favorite color?",
        exact: true,
      })
      .fill("sdf");

    await Promise.all([
      page.waitForNavigation(),
      page.getByRole("button", { name: "Continue", exact: true }).click(),
    ]);

    await Promise.all([
      page.waitForNavigation(),
      page.getByRole("button", { name: "Continue", exact: true }).click(),
    ]);

    await page
      .getByRole("button", { name: "Add household member", exact: true })
      .click();

    await page
      .getByRole("textbox", { name: "household member name #1", exact: true })
      .fill("me");

    await Promise.all([
      page.waitForNavigation(),
      page.getByRole("button", { name: "Continue", exact: true }).click(),
    ]);

    await page
      .getByRole("combobox", { name: "Month", exact: true })
      .selectOption("3");

    await page.getByRole("textbox", { name: "Day", exact: true }).fill("12");

    await page.getByRole("textbox", { name: "Year", exact: true }).fill("1956");

    await Promise.all([
      page.waitForNavigation(),
      page.getByRole("button", { name: "Continue", exact: true }).click(),
    ]);

    await Promise.all([
      page.waitForNavigation(),
      page.getByRole("button", { name: "Continue", exact: true }).click(),
    ]);

    await Promise.all([
      page.waitForNavigation(),
      page.getByRole("button", { name: "Continue", exact: true }).click(),
    ]);

    await Promise.all([
      page.waitForNavigation(),
      page.getByRole("button", { name: "Continue", exact: true }).click(),
    ]);

    await Promise.all([
      page.waitForNavigation(),
      page
        .getByRole("button", { name: "Submit application", exact: true })
        .click(),
    ]);
  } finally {
    await page?.close();
  }
}
