name: Auto Request Review

permissions: read-all

on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]

jobs:
  auto-request-review:
    name: Auto Request Review
    runs-on: ubuntu-latest
    if: github.repository_owner == 'civiform' && github.event.pull_request.head.repo.fork == false
    steps:
      - name: Request review based on files changes and/or groups the author belongs to
        uses: necojackarc/auto-request-review@e89da1a8cd7c8c16d9de9c6e763290b6b0e3d424 # v0.13.0
        with:
          # This does not use the built in GITHUB_TOKEN because we are using Github
          # teams to specify the list of reviewers. Because of that we need to
          # specify specific permissions within the personal access token
          # See: https://github.com/marketplace/actions/auto-request-review#optional-github-personal-access-token
          token: ${{ secrets.CIVIFORM_GITHUB_AUTOMATION_PERSONAL_ACCESS_TOKEN }}
          config: .github/reviewers.yml # Config file location
