name: azure_saml_ses deploy test
on:
  workflow_dispatch: {}
  pull_request:
    branches: main
    paths:
      - 'cloud/**'

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ARM_TENANT_ID: ${{ secrets.AZURE_SERVICE_PRINCIPAL_TENANT }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_SERVICE_PRINCIPAL_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_SERVICE_PRINCIPAL_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Check out branch
        uses: actions/checkout@v2

      - name: Login to Azure
        run: cloud/azure/bin/cli-login

      - name: Resolve latest snapshot tag
        run: source cloud/shared/bin/resolve-latest-snapshot-tag

      - name: Copy the config from staging
        run: |
          #  Grab the config from the staging deploy repo to confirm
          #  the changes work with actual data
          curl https://raw.githubusercontent.com/civiform/civiform-staging-deploy/main/azure_staging_civiform_config.sh > civiform_config.sh
          echo 'CIVIFORM_MODE="test"' >> civiform_config.sh

      - name: Source config, set CIVIFORM_MODE to be "test" and deploy with latest snapshot tag
        run: |
          export IMAGE_TAG="${LATEST_SNAPSHOT_TAG}"
          cloud/shared/bin/deploy
          exit $?
