name: Generate environment variable documentation markdown for release

on:
  # Need to declare separate inputs for getting manually called (workflow_dispatch) and called by the release.yaml workflow (workflow_call).
  workflow_dispatch:
    inputs:
      release_number:
        description: 'The release number to generate/update env var docs markdown for, v1.2.3 for example. IMPORTANT: the release number must already be a tag in this repo.'
        required: true
        type: string
  workflow_call:
    inputs:
      release_number:
        description: 'The release number to generate/update env var docs markdown for, v1.2.3 for example. IMPORTANT: the release number must already be a tag in this repo.'
        required: true
        type: string
    secrets:
      AUTOMATION_GITHUB_BOT_PERSONAL_ACCESS_TOKEN:
        required: true

jobs:
  generate_markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout civiform/civiform@${{ inputs.release_number }}
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.release_number }}
          path: civiform-release

      - name: Checkout civiform/civiform main
        uses: actions/checkout@v3
        with:
          path: civiform-main

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run bin/env-var-docs-generate-markdown
        env:
          LOCAL_OUTPUT: false
          ENV_VAR_DOCS_PATH: ${{ github.workspace }}/civiform-release/server/conf/env-var-docs.json
          RELEASE_VERSION: ${{ inputs.release_number }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.CIVIFORM_GITHUB_AUTOMATION_PERSONAL_ACCESS_TOKEN }}
          TARGET_REPO: civiform/docs
          TARGET_PATH: docs/it-manual/sre-playbook/server-environment-variables
        run: |
          cd civiform-main # must run bin scripts from repo root.
          bin/env-var-docs-create-venv
          bin/env-var-docs-generate-markdown
