name: Env Variable Docs - Generate

on:
  # Need to declare separate inputs for getting manually called (workflow_dispatch) and called by the release.yaml workflow (workflow_call).
  workflow_dispatch:
    inputs:
      release_number:
        description: 'The release number to generate/update env var docs markdown for, v1.2.3 for example. IMPORTANT: the release number must already be a tag in this repo.'
        required: true
        type: string
  workflow_call:
    inputs:
      release_number:
        description: 'The release number to generate/update env var docs markdown for, v1.2.3 for example. IMPORTANT: the release number must already be a tag in this repo.'
        required: true
        type: string
    secrets:
      CIVIFORM_GITHUB_AUTOMATION_PERSONAL_ACCESS_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  generate_markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout civiform/civiform main
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          path: civiform-main

      - name: Checkout civiform/civiform@${{ inputs.release_number }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ inputs.release_number }}
          path: civiform-main/civiform-release

      - name: Run bin/env-var-docs-generate-markdown
        env:
          LOCAL_OUTPUT: false
          ENV_VAR_DOCS_PATH: ./civiform-release/server/conf/env-var-docs.json
          RELEASE_VERSION: ${{ inputs.release_number }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.CIVIFORM_GITHUB_AUTOMATION_PERSONAL_ACCESS_TOKEN }}
          TARGET_REPO: civiform/docs
          TARGET_PATH: docs/it-manual/sre-playbook/server-environment-variables
        run: |
          cd civiform-main # must run bin scripts from repo root.
          bin/env-var-docs-generate-markdown
