name: pr_server

# This is a pattern for having workflows that only run when specific paths in the
# repo are edited and are required when they run, but are otherwise skipped.
# For more info see:
# https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks

on:
  pull_request:
    branches: main
    paths-ignore:
      - 'server/**'
      - 'bin/**'
      - 'browser-test/**'
      - 'test-support/**'
      - 'Dockerfile'
      - 'prod.Dockerfile'

jobs:
  run_junit_tests:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '

  run_browser_tests_aws:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '

  run_browser_tests_azure:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '

  test_prod:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '
