name: Scan for Secrets
on:
  pull_request:
  push:
  workflow_dispatch:
  # Disable due to repeated failures
  # schedule:
    # Run daily at 4AM EST / 5AM EDT / 1AM PST / 2AM PDT
    # - cron: "0 9 * * *"

permissions: read-all

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    if: github.repository_owner == 'civiform' && github.event.pull_request.head.repo.fork == false
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@e0c47f4f8be36e29cdc102c57e68cb5cbf0e8d1e # v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}
