name: tests

on:
  workflow_call:
    secrets:
      DOCKER_HUB_ACCESS_TOKEN:
        required: false
      DOCKER_HUB_USERNAME:
        required: false

  # Setting this enables manually triggering workflow in the GitHub UI
  # see https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch: { }

permissions: read-all

jobs:
  run_junit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: check out ${{ env.GITHUB_REF }}
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build test container
      env:
        DOCKER_BUILDKIT: 1
      run: docker build -t civiform-dev --cache-from docker.io/civiform/civiform-dev:latest ./
    - name: Run tests
      run: USE_LOCAL_CIVIFORM=true bin/run-test-ci

  run_browser_tests_aws:
    runs-on: ubuntu-latest
    steps:
    - name: check out ${{ env.GITHUB_REF }}
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build test app container
      env:
        DOCKER_BUILDKIT: 1
      run: docker build -t civiform --cache-from docker.io/civiform/civiform:latest ./
    - name: Build browser testing container
      env:
        DOCKER_BUILDKIT: 1
        DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      run: bin/build-browser-tests
    - name: Bring up test env with Localstack
      run: bin/run-browser-test-env --aws --ci
    - name: Run browser tests with Localstack
      run: bin/run-browser-tests-ci
    - name: Print logs on failure
      if: failure()
      run: cat .dockerlogs

  run_browser_tests_azure:
    runs-on: ubuntu-latest
    steps:
    - name: check out ${{ env.GITHUB_REF }}
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build test app container
      env:
        DOCKER_BUILDKIT: 1
      run: docker build -t civiform --cache-from docker.io/civiform/civiform:latest ./
    - name: Build browser testing container
      env:
        DOCKER_BUILDKIT: 1
        DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      run: bin/build-browser-tests
    - name: Bring up test env with Azurite
      run: bin/run-browser-test-env --azure --ci
    - name: Run browser tests with Azurite
      run: bin/run-browser-tests-ci
    - name: Print logs on failure
      if: failure()
      run: cat .dockerlogs

  test_prod:
    runs-on: ubuntu-latest
    steps:
    - name: check out ${{ env.GITHUB_REF }}
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build prod container
      env:
        DOCKER_BUILDKIT: 1
      run: docker build -f prod.Dockerfile -t civiform:prod --cache-from docker.io/civiform/civiform:latest ./
    - name: Build the stack
      env:
        SECRET_KEY: notarealsecret
      run: docker compose -f test-support/prod-simulator-compose.yml up -d
    - name: Test
      # Confirm that we get a response on port 9000.
      run: while ! docker run --network host appropriate/curl -v -s --retry-max-time 180 --retry-connrefused http://localhost:9000/ ; do sleep 5; done
      timeout-minutes: 3
