export const {
  BASE_URL = 'http://civiform:9000',
  LOCALSTACK_URL = 'http://localhost.localstack.cloud:4566',
  MOCK_WEB_SERVICES_URL = 'http://mock-web-services:8000',
  TEST_USER_AUTH_STRATEGY = '',
  TEST_USER_LOGIN = '',
  TEST_USER_PASSWORD = '',
  TEST_USER_DISPLAY_NAME = '',
  TEST_CIVIC_ENTITY_SHORT_NAME = 'TestCity',
  DISABLE_SCREENSHOTS = true,
  DISABLE_BROWSER_ERROR_WATCHER = false,
  // This value was extracted from the browser test env via:
  //
  // python -c "import requests;print(requests.Session().get('http://localhost:9999').cookies.get_dict()['PLAY_SESSION'])"
  FROZEN_PLAY_SESSION_COOKIE_VALUE = 'eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7InBhYzRqIjoiYjhPeXRPOXRrNVVWVW5UeVpINVVvUHhGNkMyQXFiN055eGtUdFZEVlRObWFOVW9pa3hpZmxRTnFGNTlyTEViY2ZhYmd1TFZ2MVM5UVBEWGp4OHJlcDhCMk9aSWkxeDQxRTdqOXRLNUdVR1lXclhOa3RwY0RDYnE2ZG9wVmFSUGFIT09lTG9FbzMvanNvdTYyZHpXd0U4bEN2OW96UWpZajdyOEJsOGFMWGVjeDdjNWlhcnVwb0xSN3d0WkZXSUVicVNIOTNIWkJILzVJS3dRZzVreXEvaGFNVCt6NHRuVUptR2FVU3FSK1R6NTNkNVF1dUt0TVVaWVJlNlZXL1YvdFErbFRsY2l2RTZnQ3VSdGEwQVN2U3hDMFZ2SUNSbklKTjJJWk1MRGd4Qk04Z2xiSFFmcWczblFPL2RxeTdJbENEQ0wwUUpmREp4V01zMFRmQ2hod1FpRFRHUmkwVE9mcXZoc2dQemlFWklTdTkrZGM3M0RkVzZZakJpU2V1dzkvMWxibnk4bFNOK1AwUWw1MXliQmdpaUxaZFdkWGkya3NaSnhjTkFKVDBXV2M0T3hxaTR5MFBQVGJuYUNJQ0tNbkMrNWxNZCtOd2VaRU9oRkFjYXNOWXc9PSIsImNzcmZUb2tlbiI6IjAwNmUxZDAyYTdmYWZlZjEwZjQzM2M1YjIwNmM0NGMyZGQzNDAwNWUtMTc4MzM1MTEzMzU2NC05Yzk1ZTRiZDBkZDY0YjY0OGQyZTA1ODcifSwibmJmIjoxNzgzMzUxMTMzLCJpYXQiOjE3ODMzNTExMzN9.kyJj-ACnHOlF9dwagkkKjQbK23dMRKZl2RhoM_iA4Jw', // gitleaks:allow
} = process.env
