export const {
  BASE_URL = 'http://civiform:9000',
  LOCALSTACK_URL = 'http://localstack:4566',
  TEST_USER_AUTH_STRATEGY = '',
  TEST_USER_LOGIN = '',
  TEST_USER_PASSWORD = '',
  TEST_USER_DISPLAY_NAME = '',
  TEST_CIVIC_ENTITY_SHORT_NAME = 'TestCity',
  DISABLE_SCREENSHOTS = false,
  DISABLE_BROWSER_ERROR_WATCHER = false,
} = process.env
